MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,c,b){c||(c="load");b||(b=window);b.attachEvent?b.attachEvent("on"+c,a):b.addEventListener(c,a,false)}function json(a){try{return eval("("+a+")")}catch(c){return null}}function _65(a){if(!a||typeof a=="string")return a;var c="",b;for(b in a)c+="&"+b+"="+encodeURIComponent(a[b]);c&&(c=c.substr(1));return c}
function ajax(a){var c=/POST/i.test(a.type),b=a.data||"",d=a.dataType,f=a.url||location.href,e=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,d=="json"&&(b=json(b)),(c=a.success)&&c(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var l=[],j;for(j in b)l.push(encodeURIComponent(j)+"="+encodeURIComponent(b[j]));b=l.join("&")}g.open(c?
"POST":"GET",f+(c?"":(b?e:"")+b+(a.cache?"":(!b&&e=="?"?"?":"&")+(a.cache_ok?"":"_="+(new Date).getTime()))),a.async===false?false:true);c&&g.setRequestHeader("Content-Type","application/x-www--urlencoded");g.send(b);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.jsonp_callback=a.jsonp_callback||"callback";a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");var c=(new Date).getTime();window.hashOptions=window.hashOptions||{};window.hashOptions[c]=a;window.hashOptions[""]=a;a.cache_ok||(a.url+=a.url.indexOf("?")>-1?"&":"?",a.url+="_mats="+c,a.url+="&callback="+a.jsonp_callback);
if(a.type=="jsonp"){window[a.jsonp_callback]=function(a){window.hashOptions[a._mats||""].success(a)};var b=document.getElementsByTagName("head")[0],d=document.createElement("script");d.type="text/javascript";d.src=a.url;d._mats=c;d.onload=function(){};d.onerror=function(){window.hashOptions[this._mats||""].error({status:-2,desc:"Failed to load the url: "+a.url})};b.appendChild(d)}else{var f;window.XMLHttpRequest?f=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});f.onreadystatechange=
function(){if(f.readyState==4)if(f.status==200){var b="ok";if(a.type=="json")try{a.success(JSON.parse(f.responseText))}catch(c){b=c.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+b+")"})}else a.type=="data"?a.success(f.response):a.type=="text"&&a.success(f.responseText)}else a.error({status:f.status,desc:"Error in fetching data (code "+f.status+")"})};if(a.type=="data")f.responseType="blob";f.open(a.method,a.url,true);f.send()}};
function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}function fo(a){var c=0,b=0;do c+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:c,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}
function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,c){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),d=c?document.getElementsByTagName(c):document.getElementsByTagName("*")||document.all,f=[],e=0,g=d.length;e<g;e++)b.test(d[e].className)&&f.push(d[e]);return f}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var c=0,b=0;a&&a.tagName!="BODY";)c+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:c,left:b}}var MugedaTools=window.MugedaTools=window.MugedaTools||{};
MugedaTools.message=function(){var a,c=[],b={},d=function(){var a=window.getComputedStyle(document.documentElement,""),a=(Array.prototype.slice.call(a).join("").match(/-(moz|webkit|ms)-/)||["",""])[1];return{dom:"WebKit|Moz|MS".match(RegExp("("+a+")","i"))[1],lowercase:a,css:"-"+a+"-",js:a[0].toUpperCase()+a.substr(1)}}();return{show:function(f){var e=document.createElement("div"),g=e.appendChild(document.createElement("div")),l=g.appendChild(document.createElement("div")),j=g.appendChild(document.createElement("div"));
e.style.cssText="position:fixed;left:0;right:0;top:0;bottom:0;text-align:center;line-height:"+(document.body.clientHeight||document.documentElement.clientHeight)+"px";g.style.cssText='padding-top:10px; line-height:30px;display:inline-block;padding:8px; min-width: 80px; background-color:rgba(0,0,0,0.6);border-radius:4px;"';g.align="center";l.style.cssText="width: 24px; height: 24px; display: block; border-radius: 50%; border-left: 2px solid #F36523; border-top: 2px solid #F36523; border-right: 2px solid white; border-bottom: 2px solid white; margin: 16px;";
j.style.cssText='text-align:center;color:#fff;font:normal 12px "microsoft yahei";';j.innerHTML=f;a=document.body.appendChild(e);g="from {"+d.css+"transform:rotate( 0deg ) }to {"+d.css+"transform:rotate( 360deg ) }";f=document.createElement("style");document.head.appendChild(f);f=f.sheet;e="spin_"+(new Date).getTime();g="@"+d.css+"keyframes "+e+"{ "+g+"}";if(c.length){var j=c.pop().name,i=b[j];delete b[j];f.deleteRule(i);f.insertRule(g,i);b[e]=i}else{j=f.cssRules.length;try{f.insertRule(g,j)}catch(t){}b[e]=
j}l.style.cssText+=d.css+"animation:"+e+" 1200ms linear infinite;"},close:function(){a&&(a.parentNode.removeChild(a),a=null)}}}();
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if((a.id||"").indexOf("_stage")>0||a.getAttribute&&a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var c=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var d=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(c!="expand"&&b!="interstitial"&&d)d.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(c=="auto"||c=="expand"||c=="interstitial")&&setTimeout(function(){d.style.display="block"},50);break;case "resized":setTimeout(function(){d.style.display="block"},50)}},openLink:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);if(a){var b="ts="+(new Date).getTime();b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+encodeURIComponent(_mrmcp.title||"");var d=_mrmcp.custom_params;d&&d.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+d);if((d=_mrmcp.redirect_url)&&d.indexOf("%LINK%")<0)var f=a.indexOf("?"),e=f<0?"?":"&",a=d+(d.lastIndexOf("=")==d.length-1?encodeURIComponent(a+e+b):"");e=a.split("#");
d="";e.length>1&&(d=e[1],a=e[0]);var f=a.indexOf("?"),e=f<0?"?":"&",f=f==a.length-1,g=window.location.search;if(g){for(var g=g.split("?")[1],l=g.split("&"),j=l.length,i=0;i<j;i++){var t=l[i].split("=");if(t.length==2){var r=t[1];t[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(r),f=a.indexOf("?"),e=a<0?"?":"&",f=f==a.length-1)}}a+=(f?"":e)+g;f=false;g.length&&(e="&")}a+=(f?"":e)+b+(d?"#"+d:"");this.mraidReadyStatus==1?c=="internal"?mraid.open(a):c=="expand"?this.expand(a,0):window.open(a):c==
"internal"?window.location=a:c=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",action:c,label:a,value:0})}},expand:function(a,c,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var d=document.URL.match(/client.*preview.*id/),f=b=null;try{b=(d?window:window.parent).document,f=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(e){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||
"")+a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(b.defaultView.innerWidth||b.documentElement.clientWidth)+"px";f.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;'></iframe>";b.body.appendChild(f);
MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},f=mraid.getMaxSize(),d=parseInt(b.width)||f.width,f=parseInt(b.height)||f.height,a=a||b.url,g=!a||a.length==0;c==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:d,height:f,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:d,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):
mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,
c){if(a){var b="_"+ +new Date,d=0,f=0;a.data&&(b="_"+a.data.guid,a.data.param&&(d=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var e=G("mugeda_video"+b);if(e)return e.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0.8)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";_mrmcp=typeof _mrmcp==
"undefined"?{}:_mrmcp;var g=(_mrmcp.creative_path||"")+"close_button.png",l=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+b+'" preload="auto" webkit-playsinline="true" video-id="'+c.id+'"  video-mode="'+c.mode+'" video-name="'+c.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;"></video>'+('<div id="mugeda_video_close'+b+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+
(l?0:0)+"px;cursor:pointer;background-image:url("+g+');z-index:3;"></div>');a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);e=G("mugeda_video"+b);b=G("mugeda_video_close"+b);b.style.display=c.close_button?"block":"none";c.close_button&&(g=isMobile()?"touchend":"click",b.addEventListener(g,function(a){a.stopPropagation();e.src="";e.rawSrc="";e.load();div.style.display="none"},false));c.video_controls?e.setAttribute("controls","controls"):e.removeAttribute("controls");e.rawPlay=e.play;
e.rawPause=e.pause;e.play=function(){e.paused&&(e.onplayed(),e.rawPlay())};e.pause=function(){e.onpaused();e.rawPause()};e.onplayed=function(){if(d==0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};e.onpaused=function(){if(d==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};e.onclick=function(a){a.preventDefault();
a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&this.play()};return div}},loadUrl:function(a){var c=a.id||(new Date).getTime(),b=a.url||"",d=a.left||0,f=a.top||0,e=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),l=a.before||null,j=a.style,i=a.scroll,t=a.parent,r=a.onload,h=a.onclose,k=a.position,q=a.close_position;if(!l&&!t){var p=typeof Mugeda!="undefined"&&Mugeda.getCanvas?
Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&p&&(p=getElementOffset(p),d+=p.left,f+=p.top)}var m=G(c);m||(m=document.createElement("div"),t?t.appendChild(m):l?l.parentNode.insertBefore(m,l):document.body.appendChild(m));m.id=c;m.style.margin=0;m.style.padding=0;m.style.backgroundColor="transparent";m.style.position=k?k:"fixed";m.style.top=0;m.style.left=0;m.style.width=0;m.style.height=0;switch(q){case "leftTop":q="left:4px;top:4px;";break;case "leftbottom":q="left:4px;bottom:4px;";
break;case "rightbottom":q="right:4px;bottom:4px;";break;default:q="right: 4px;top: 4px;"}m.innerHTML="<iframe "+(i?"":"scrolling=no ")+'id="'+c+'_iframe" style="border:none; width:100%;height:100%; '+(i?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+c+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+q+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');
m.style.display="none";m.style.top=f+"px";m.style.left=d+"px";m.style.width=e+"px";m.style.height=g+"px";m.style.display="block";m.style.cssText+=j;G(c+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(c+"_iframe_close").onclick=function(){m.style.display="none";G(c+"_iframe").src="about:blank";h&&h(m)}},100);setTimeout(function(){var a=G(c+"_iframe");a.src=b;if(r)try{a.onload=function(){r(a);a.onload=null}}catch(e){}},100);return m},playAudio:function(a,
c){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var d=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(d){if(d.loop=parseInt(a.audio_loop)==1?true:false,d.play)if(d.webAudio)b=d.play(a.event=="click"||c?true:false);else if(a.event=="click"){try{d.pause(),d.currentTime=0}catch(f){}setTimeout(function(){d.play()},5)}else(d.playStatus!=1||c)&&setTimeout(function(){d.play();d.playStatus=1;b=true},
10)}else{var d=new Audio,e=document.createElement("source"),g=a.audio_url.lastIndexOf("."),g=a.audio_url.substring(g+1),l=true;switch(g){case "ogg":e.type="audio/ogg";break;case "mp3":e.type="audio/mpeg";break;default:l=false,console.log("Audio extension ("+g+") not supported.")}if(l){e.src=a.audio_url;d.appendChild(e);d.autoplay=false;d.preload="auto";d.load();var j=document.getElementById("mugeda_resource_loading");if(!j)j=document.createElement("img"),j.id="mugeda_resource_loading",j.style.position=
"fixed",j.style.right="2px",j.style.top="2px",j.style.display="block",j.src=(_mrmcp.creative_path||"")+"loading.gif",document.body.appendChild(j);j.style.display="block";b=true;d.addEventListener("canplay",function(){j.style.display="none";d.play()},false);MugedaBehavior.localCache[a.audio_url]=d}}return b},playHTML5Video:function(a){var c=a.left||0,b=a.top||0,d=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",e=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():
this.getStage();typeof Mugeda!="undefined"&&e&&!a.video_holder&&!isNaN(a.left)&&(e=getElementOffset(e),c+=e.left,b+=e.top);var g=document.body;if(a.video_holder)if((e=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&e.scene){var g=a.video_holder,g=g.split("/"),l=a.video_object===1;if(g.length===2)e=e.scene.getObjectByName(l?g[1]:g[0]),l?(g=e?e.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=e?e.scene.getObjectByName(g[1]):null;else if(l){if((g=e.scene.objectHash[a.video_holder])||
(g=e.scene.dom.querySelector('*[data-guid="'+a.video_holder+'"]')),g&&g.data)a.url=g.data.param.videoUrl}else g=e.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&(e=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=e.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;e=this.createHTML5VideoTag(g,a);e.style.top=b+"px";e.style.left=c+"px";e.style.width=d;e.style.height=f;e.style.display=
"block";var j=e.querySelector("video");j.src=a.url;j.rawSrc=a.url;j.load();setTimeout(function(){j.play();j.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=1){var c=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&a.video_id&&c&&c.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,
left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,10)==1,auto:parseInt(a.video_autoplay,10)==1})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),c=0,b=a.length;c<b;c++){var d=a[c].querySelector("video");if(d)d.src="",d.rawSrc="",d.load();a[c]&&(a[c].style.display="none")}},
controlVideo:function(a,c){var b=document.querySelector("#mugeda_video_"+a);if(b)if(c=="play")b.play();else if(c=="pause")b.pause();else{if(c=="stop")b.pause(),b.currentTime=0}else if((b=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&b.scene)if(b=b.scene.objectHash[a]){var d=b.data.param;c==="play"&&MugedaMraid.playVideo({auto:d.videoAutoPlay,clickStatus:d.clickStatus,event_name:"",hidePlayIcon:d.hidePlayIcon,video_close:0,video_continue_audio:d.continueAudio,video_controls:d.hidePlayControls==
1?0:1,video_holder:b.data.guid,video_left:0,video_mode:"object",video_name:d.name,video_object:1,video_top:0,video_url:d.videoUrl})}},sendShortMessage:function(a){var c="sms:"+a.phone_number;if(a.sms_body){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1;c+=(b?"?":"&")+"body="+a.sms_body}window.open(c,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,c){if(window&&c.name&&c.name.length&&window[c.name])window[c.name](a,c.key,c.value)},map:function(a){var c=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),d=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),e=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,e=a.length;b<e;b++)a[b]&&(a[b].style.display="none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),b=window._mrmcp&&_mrmcp.creative_path?
_mrmcp.creative_path+"loading.gif":"/images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},l=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},j,i,t=function(a,
b,e,c){j||(j=new BMap.Map("mugedaMap-con"));j.centerAndZoom(e||"\u5317\u4eac",11);j.addControl(new BMap.ZoomControl);i||(i=new BMap.LocalSearch(j,{renderOptions:{map:j,autoViewport:true},onSearchComplete:function(a){typeof c==="function"&&c.call(j,a)}}));b&&a?i.searchNearby(b,a):i.search(b)},r=function(a,b,c){if(f===0){var d=["http://api.map.baidu.com/getscript?type=quick&file=api&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0","http://api.map.baidu.com/getscript?type=quick&file=feature&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0"],
b=decodeURIComponent(b),a=decodeURIComponent(a);e();l(1);for(var g=0,c=0,j=d.length;c<j;c++){var i=document.createElement("script");i.src=d[c];i.onload=function(){++g===j&&t(a,b,"",function(a){a.getNumPois()===0&&Mugeda.messageBox("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f","alert");l(0)})};document.head.appendChild(i)}}else if(d="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",i=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||
[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,c==1){if(c=document.getElementById("aMugedaGeoLocation"))c.href=d,d=document.createEvent("HTMLEvents"),d.initEvent("click",true,true),c.dispatchEvent(d)}else i&&i<6?window.location.href=d:window.open(d,"_blank")};if(!d&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;r(c,b,1)})}else r(c,b)},popupForm:function(a,c){function b(a,b){if(a&&b)return a.querySelector("#"+b)}function d(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,c,e,d=document.cookie.split(";");for(b=0;b<d.length;b++)if(c=d[b].substr(0,d[b].indexOf("=")),e=d[b].substr(d[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),c==a.toLowerCase())return unescape(e);
return""}function f(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(b))}catch(c){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var e=new Date;e.setDate(e.getDate()+3);e=escape(b)+"; expires="+e.toUTCString();document.cookie=a.toLowerCase()+"="+e}}function e(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(c){var b=
function(a,b){Array.prototype.forEach.call(a,function(a,c){b(a,c)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",
setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),e(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var l=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!l&&!a.url)){var l=document.documentElement.clientWidth,j=document.documentElement.clientHeight,i=[],t=function(b,c){var c=c||{},e=c.detail,d=c.form||(e?e.form:null),
e={item:e,form:d,title:a.title,hideItem:function(a){d&&d.elements[a]&&(d.elements[a].parentNode.style.display="none")},showItem:function(a){d&&d.elements[a]&&(d.elements[a].parentNode.style.display="block")}},c=document.createEvent("Events");c.initEvent(b,true,true);c.detail=e;window.dispatchEvent(c)};window.addEventListener("_mugedaFormChanged",function(a){t("mugedaFormChanged",a)});var r=a.items||[];window.popupFormFields=r;if(!a.html){var h="";c?(h+='<div class="popupFormContent">',a.title&&(h+=
'<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(h+='<div align="center" class="popupFormTitle">',h+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',h+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",h+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',h+="</div>",
h+='<div class="popupFormContent">');var k=navigator.userAgent.toLowerCase(),q=k.indexOf("android")>-1,p=parseFloat(k.slice(k.indexOf("android")+8)),m="",y=0,z={phone:"tel",input:"text"};q&&p<3&&(m="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var B=c?"":":",k=0;k<r.length;k++){var n=r[k],x=(n.value||"").trim();if(x){for(var x=x.split("\n"),u=[],v=0;v<x.length;v++){var I=x[v].split("("),A=I[0],I=(I[1]||"").replace(/\)$/,"")||A,F=["FORMID",I,k,v].join("_");u[v]={id:F,
text:A,value:I}}x=u}F='id="popupFormField_'+k+'"';switch(n.type){case "radio":h+="<div "+F+' class="popupFormRadioList">';n.description&&(h+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");h+='<div class="mformradio">';for(v=0;v<x.length;v++)u=x[v],A=d(u.id),h+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+n.id+'" value="'+
u.value+'" id="'+u.id+'" '+(A=="true"?"checked=checked":"")+" ><span "+(v==x.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+u.text+"</span></label>",i[u.id]=u.id;h+="</div></div>";break;case "checkbox":h+="<div "+F+' class="popupFormCheckbox">';n.description&&(h+='<label class="inputlabel">'+n.description+(n.required?"*":"")+B+"</label>");h+='<div class="mformcheck">';h+=n.rangeType==="vertical"?"<table>":"";for(v=0;v<x.length;v++)u=x[v],A=d(u.id),h+=n.rangeType==="vertical"?
'<tr><td><input type="checkbox" value="'+u.value+'" id="'+u.id+'" '+(A=="true"?"checked=true":"")+' ></td><td><label for="'+u.id+'" >'+u.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+n.id+'" value="'+u.value+'" id="'+u.id+'" '+(A=="true"?"checked=true":"")+' ><label for="'+u.id+'" >'+u.text+"</label>",i[u.id]=u.id;q&&p<3&&n.rangeType!=
"vertical"&&(y=6);h+=n.rangeType==="vertical"?"</table>":"";h+="</div></div>";break;case "select":h+="<div "+F+' class="popupFormSelectList">';n.description&&(h+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+"</label>");h+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+n.id+'" id="'+("_map_"+n.description)+'">';h+='<option value="">'+n.description+
"</option>";A=d(n.description);for(v=0;v<x.length;v++)u=x[v],h+='<option value="'+u.value+'" '+(A==u.value?"selected=selected":"")+">"+u.text+"</option>";h+="</select>";h+="</div>";i[n.description]="_map_"+n.description;break;case "textarea":h+="<div "+F+' class="popupFormInputBox">';h+='<label class="inputlabel inputlabel_area">'+n.description+(n.required?"*":"")+B+'</label><textarea name="'+n.id+'" id="_mcp_'+escape(n.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(n.value.length?n.value:d(n.description))+"</textarea>";h+="</div>";i[n.description]="_mcp_"+escape(n.description);break;default:h+="<div "+F+' class="popupFormInputBox">',h+='<label class="inputlabel text">'+n.description+(n.required?"*":"")+B+'</label><input class="text" name="'+n.id+'" id="_mcp_'+escape(n.description)+'" type="'+(z[n.type]||n.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(d(n.description)||n.value)+'" '+(c?'placeholder="'+n.description+'"':"")+">",h+="</div>",i[n.description]="_mcp_"+escape(n.description)}}c&&(h+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',h+='<input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>');h+="</div>";a.html=h}delete this.popupFormDiv;var o=this.popupFormDiv;if(!o){k=function(b){var b=b||".popupForm",e=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))e=
RegExp.$1;e="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {padding-bottom:16px; background-color:#fff;opacity:"+e+";}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;position:relative;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+
b+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+m+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+
b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+y+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";c&&(e+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",e+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",e+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+
a.color+";display:none;background-color:"+a.background+"}");e+="</style>";return e};if(!o){var J=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,o=document.createElement("div");o.style.display="none";o.className=c?"popupForm2":"popupForm";var C="";if(c)var D=function(b){for(var e={l:48,r:200},c=0,d=0,g=b.length;d<g;d++){for(var f=b[d],j=f.description.length,i=0,h=0;h<j;h++)i+=f.description[h].match(/[\u3400-\u9FBF]/)?2:1;c=Math.max(c,i)}c=c>8?8:c;b=a.fontSize*(c-4);c>4&&c<=8&&(e.l+=b,e.r-=
b);return e}(r),C=k(".popupForm2");else C=k();o.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+C;!c&&!a.isCss?document.body.appendChild(o):(a.hwObj=D,a.iframeDiv=o,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=o;o.form=o.childNodes[0];o.form.onclick=function(){};self=this;c||o.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==
o)g(o),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),c=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&c!="checkbox"&&c!="submit"&&(a.target.focus(),q&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());c=="button"&&a.stopPropagation()}});C=function(){function e(){var d=[],f=r;if(!c)f=window.popupFormFields;for(var j=0;j<f.length;j++){var i=f[j],
h=b(o,"popupFormField_"+j),l="",k=h.querySelectorAll("select");k.length==0&&(k=h.querySelectorAll("textarea"),k.length==0&&(k=h.querySelectorAll("input")));if(k.length==1)l=k[0].value||"";else if(k.length>1){for(var l=[],m=0;m<k.length;m++)if(h=k[m],h.checked&&(l.push(h.value),h.type=="radio"))break;l=l.join(",")}if(i.required&&!l){Mugeda.messageBox((i.description||"item")+" required");k[0].focus();return}if(l)switch(i.type){case "phone":if(!/^\d+$/.test(l)){Mugeda.messageBox((i.description||"Phone number")+
" required");k[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(l)){Mugeda.messageBox((i.description||"Email")+" required");k[0].focus();return}}a.openTarget==="default"?d.push(encodeURIComponent(i.description+"("+i.id+")")+"="+encodeURIComponent(l||"")):d.push(encodeURIComponent(i.id)+"="+encodeURIComponent(l||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;d=d.join("&");f=a.url+"?"+d;a.loadFinished=function(){g(o);self.popupFormDiv=
null};if(a.openTarget=="customizable")f={callback:function(b){a.msg?Mugeda.messageBox(a.msg,"alert",function(){window.open(b,"_self")}):window.open(b,"_self")},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(d,f),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){j="";f=0;if(window._mrmcp)j=window._mrmcp.creative_id||"";else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)j=Mugeda.data.crid;
if(j==""&&/\/edit\/(\w+)\&?/.test(top.location.href))j=RegExp.$1,f=j.length<16?1:2;else if(j==""&&/id=(\w+)\&?/.test(window.location.search))f=3,j=RegExp.$1;i=function(a,b,c){var c=c||"post",e=document.createElement("form"),d=document.createElement("iframe");e.setAttribute("method",c);e.setAttribute("action",a);a="__iframe"+Math.random()*1E4;d.setAttribute("id",a);d.setAttribute("name",a);e.setAttribute("target",a);d.style.width=0;d.style.height=0;d.style.display="none";d.addEventListener("load",
function(){});a=0;for(c=b.length;a<c;a++){var f=b[a].split("="),j=f[0],f=f[1],g=document.createElement("input");g.setAttribute("type","hidden");g.setAttribute("name",j);g.setAttribute("value",f);e.appendChild(g)}document.body.appendChild(e);document.body.appendChild(d);e.submit()};if(j&&/^[a-zA-Z0-9\-\_\.]+\.(mugeda|mgd5|h5mc)\.com$/.test(window.location.hostname))window._mrmcp=window._mrmcp||{},i(_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform",(d+"&crid="+j+"&mode="+f).split("&")),
a.msg&&Mugeda.messageBox(a.msg);a.openTarget=="callback"?a.callback&&window[a.callback]?(f={callback:function(){a.msg&&Mugeda.messageBox(a.msg)},cancel:false},window[a.callback](d,f),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),f.cancel!==true&&f.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(f,
J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0});a.msg&&Mugeda.messageBox(a.msg)}}catch(n){a.loadFinished(),Mugeda.messageBox("Form submission failed. Please try again. ")}}o.querySelector("#popupFormIframe").onload=null;for(n in i){var d=document.getElementById(i[n]);d&&(d.type=="checkbox"||d.type=="radio"?f(n,d.checked):f(n,d.value))}p<3?e():setTimeout(e,200);return false}}o.style.display=
"";o.form.innerHTML=a.html;if(a.id)o.form.id=a.id;var K=isMobile()?"touchstart":"click";o.form.querySelector("input[id=actionButton]").addEventListener(K,C,false);o.style.display="";o.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:o.form});o.style.visibility="visible"},200);setTimeout(function(){b(o,"popupFormCancel").addEventListener(K,function(){g(o);self.popupFormDiv=null},false)},500);D=o.querySelectorAll(".popupFormInput");for(k=0;k<D.length;k++)C=D[k],C.onfocus=
onInputFocus,C.onblur=onInputBlur;var w;a.target?w=a.target.getBoundingClientRect():(D=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?(l=D.adaption,w={left:Math.max(0,(window.Mugine?1:-1)*l.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*l.marginTop),width:Math.min(l.width,D.width),height:Math.min(l.height,D.height)}):w={left:0,top:0,width:l,height:j};document.body.style.overflowY="auto";if(e()){if(o.style.marginLeft=Math.max(2,w.left+document.documentElement.scrollLeft+
(w.width-o.offsetWidth)/2)+"px",o.style.marginTop=Math.max(2,w.top+document.documentElement.scrollTop+(w.height-o.offsetHeight)/2)+"px",o.style.marginBottom="32px",o.offsetHeight+32>document.documentElement.scrollHeight&&(o.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(o).marginTop:o.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=o.offsetHeight+64+"px"}else if(o.style.position="relative",o.style.left=w.left+"px",o.style.top=w.top+"px",Math.max(2,w.top+(w.height-
o.offsetHeight)/2),Math.max(2,w.left+(w.width-o.offsetWidth)/2),!c){var H=o.querySelector("form");H.style.bottom="-9999px";o.style.overflow="hidden";setTimeout(function(){o.style.background="rgba(0,0,0,0)";o.style.width=w.width+"px";o.style.height="100%";H.style.webkitTransition="none";H.style.bottom=-H.offsetHeight+"px";setTimeout(function(){H.style.webkitTransition="all 500ms";H.style.bottom="0px";H.style.overflowY="auto";!c&&(o.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var c=
a.items,b=0,d=0,f=c.length;d<f;d++){var e=c[d];switch(e.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=64;break;case "radio":b+=48;break;case "checkbox":e=e.value.split("\n").length;b+=32*e+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,c,b,d){var f=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();
else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var e=a.param&&a.param.page_number?a.param.page_number:a.param,g=typeof e=="string"?e.split(";"):[];g.length>1&&(e=g[Math.floor(Math.random()*g.length)]);e=parseInt(e);this.gotoPage(e)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type==
"gotoAndPlay")e=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof e=="string"?e.split(";"):[],g.length>1&&(e=g[Math.floor(Math.random()*g.length)]),e=parseInt(e),isNaN(e)&&(e=a.param&&a.param.frame_name?a.param.frame_name:"",e=Mugeda.mapFrameNameId[e],e=parseInt(e)+1),this.gotoAndPlay(e);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")e=a.param&&a.param.frame_number?a.param.frame_number:a.param,g=typeof e=="string"?e.split(";"):[],g.length>1&&(e=g[Math.floor(Math.random()*
g.length)]),e=parseInt(e),isNaN(e)&&(e=a.param&&a.param.frame_name?a.param.frame_name:"",e=Mugeda.mapFrameNameId[e],e=parseInt(e)+1),this.gotoAndPause(e);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type=="audio")a.param.event=c,f=a.restart,window.Mugeda&&
Mugeda.getMugedaObject&&(e=Mugeda.getMugedaObject(),e=Math.floor(e.scene.currentId),a.unit&&a.unit.frameStart==e&&(f=true)),f=MugedaMraid.playAudio(a.param,f);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&
Mugeda.stopAudioAll();else if(a.type=="submitForm"){var l=a.param,e=a.mugeda,g=l.submit_object,j=l.submit_target||0;window._mrmcp=window._mrmcp||{};var l=j==0?_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform":l.submit_url,i="",j=0;if(window._mrmcp&&window._mrmcp.creative_id)i=window._mrmcp.creative_id;else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)i=Mugeda.data.crid,j=3;if(i==""&&/\/edit\/(\w+)\&?/.test(top.location.href))i=RegExp.$1,j=i.length<16?1:2;else if(i==""&&/id=(\w+)\&?/.test(window.location.search))j=
3,i=RegExp.$1;if(i&&g){for(var g=g.split(","),j="crid="+i+"&mode="+j,i={},t=0,r=0;r<g.length;r++){var h=g[r],k=e.scene.getObjectByName(h);if(k)if(k.data.type===2041){var q=k.data.param.name;if(q){var p=k.data.param.required,h=k.dom.querySelector("input:checked");if(p===1&&!h){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+q+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else i[q]=h?h.value:"",t++}}else if(k.data.type===2038){if(q=k.data.param.name)if(p=k.data.param.required,h=document.querySelectorAll("input[name="+
q+"]:checked"),p===1&&!h.length){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+q+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");return}else{for(var p=[],k=0,m=h.length;k<m;k++)p.push(h[k].value);i[q]=p.length?p.join(","):"";t++}}else if(k.data.type===2039)if(p=k.data.param.required,m=unescape(k.data.param.textContent),k=k.dom.querySelector("option:checked"),p===1&&k&&k.innerText===m){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+m+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");
return}else j+=k?"&"+h+"="+(k.value!==m?k.value:""):"&"+h+"=",t++;else{var m=k?k.text||"":"",y=k.data.param.inputType,z={tel:"^\\d+$",email:'^(([^<>()\\[\\]\\\\.,;:\\s@"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@"]+)*)|(".+"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$',date:"",time:"",number:"^\\d+$"},p=k.data.param.required;if(p===1&&!m.length){Mugeda.messageBox("\u8bf7\u9009\u62e9\u3010"+k.data.param.name+"\u3011\uff0c\u8be5\u9879\u4e0d\u80fd\u4e3a\u7a7a\u3002");
return}else if(m.length&&(p=z[y])&&!RegExp(p).test(m)){Mugeda.messageBox("\u3010"+k.data.param.name+"\u3011\u7684\u5185\u5bb9\uff08"+m+"\uff09\u7684\u683c\u5f0f\u4e0d\u6b63\u786e\u3002\u8bf7\u68c0\u67e5\u540e\u91cd\u8bd5\u3002");return}h&&(h=h.replace(/#/g,"_"),j+="&"+h+"="+m,t++)}}if(t==0)return;l+="?"+j;if(Object.keys(i).length>0)for(q in i)l+="&"+q+"="+i[q];MugedaTools.message.show("\u6b63\u5728\u63d0\u4ea4");ajaxHelper({url:l,type:"jsonp",jsonp_callback:"form_callback",success:function(a){MugedaTools.message.close();
d&&d(a)},error:function(){MugedaTools.message.close();d&&d({status:-1})}})}}e="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)e+="&"+item+"="+a.param[item];c=="click"&&window.event&&window.event.stopPropagation&&window.event.stopPropagation();f&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",action:a.param.event_name,label:e,value:0})},processCloseButton:function(a,c){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=c,d=null;if(!b)try{window!=window.parent?
(b=window.parent.document,d=window.frameElement):b=document}catch(f){b=document}if(b){var e=null;try{e=window.parent.document,e.getElementById("mugeda_expanded")||e.createElement("div")}catch(g){return}var l=a||_mrmcp.display_mode,j=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",i=b.getElementById("mugeda_close_button");if(!i)i=b.createElement("img"),i.id="mugeda_close_button",i.style.cursor="pointer",i.style.zIndex=99999,i.style.display="block",i.style.position="fixed",i.style.right=
"0",i.style.top="0",i.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(i);l=="interstitial"&&d&&d.parentNode.removeChild(d);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),b.body.appendChild(i);if(j=="interstitial"||l=="auto"||l=="resize"||l=="expand"||l=="interstitial")i.src=(_mrmcp.creative_path||"")+"close_button.png",i.onerror=function(){i.style.display="none"},i.onload=function(){i.style.display=j=="interstitial"||l!="auto"?"block":
"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,c,b){function d(a){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1,e=b?15:20,d=b?5:10,t=function(a,g,h,k){if(Math.sqrt(a*a+g*g+h*h)>=(k?e:d)){a=(new Date).getTime();g=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||g>200)MugedaBehavior.shakeNum++,MugedaBehavior.lastHitTime=a;else if(g>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(b?1:2)){for(var t in MugedaBehavior.shakeHash){a=
MugedaBehavior.shakeHash[t];for(g=0;g<a.length;g++)info=a[g],h=info.object,h=h.displayObject?h.displayObject.realVisible:true,info.callback&&h&&(MugedaBehavior.processAction(info.behavior,info.behavior.event,true),info.callback())}MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,c.event);MugedaBehavior.shakeNum=0}}},r=0,h=0,k=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||
a.acceleration.z===null){if(a.accelerationIncludingGravity)r=a.accelerationIncludingGravity.x,h=a.accelerationIncludingGravity.y,k=a.accelerationIncludingGravity.z,t(r,h,k,1)}else r=a.acceleration.x,h=a.acceleration.y,k=a.acceleration.z,t(r,h,k,0)}var f=a.dataRef||a.aniData;isMobile();isMobile();isMobile();if(c.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",d,false),window.mugedaShakeHooked=true;var e=a.aniData?
a.aniData.guid:null;e&&(MugedaBehavior.shakeHash[e]||(MugedaBehavior.shakeHash[e]=[]),MugedaBehavior.shakeHash[e].push({object:a,callback:b,behavior:c}))}}};

function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$23){alert(e$$23.toString())}
function genSessionId(a){for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=Number(+new Date).toString(36),d=0,f="",e=c.length;d<a;d++)f+=c[Math.floor(Math.random()*e)];return b+f.toLowerCase()}Mugeda=window.Mugeda||{};
Mugeda.playEmbeddedVideo=function(a){a=a.target.parentElement;a.style.display="none";for(var c=0;c<a.parentElement.children.length;c++)a.parentElement.children[c].setAttribute("contenteditable","false");var b=a.previousSibling;b.play();b.onclick=function(){b.controls=b.paused?false:true;b.paused?b.play():b.pause()};if(navigator.userAgent.match(/mqqbrowser.*tbs/i)){for(var d=null;;)if(a=a.parentElement,a.className.indexOf("mugeda_richText_content")>=0){d=a.parentElement;break}else if(a==document.body)break;
var a=d.scrollTop,f=document.createElement("div");f.className="qbrowser_workaround";f.style.position="absolute";f.style.width="1px";f.style.height="1px";f.style.left=0;f.style.top=a+"px";d.appendChild(f);if(d)d.onscroll=function(){f.style.top=d.scrollTop+"px"}}};
Mugeda.Analytics=function(a,c){var b=[],d=0;window._mrmcp=window._mrmcp||{};var f=_mrmcp.impression_pixel?_mrmcp.impression_pixel.indexOf("%TRACKURL%")>=0?"":_mrmcp.impression_pixel:"",a=a||f||"http://cn-stat.mugeda.com/stats/c.gif",c=c||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,e,c){a=a||0;b[a]&&delete b[a];b[a]={};b[a][e]=c||""};var e=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=
document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},g=function(){e("clientId");for(var a=[],c=0;c<b.length;c++)for(var d in b[c])a[c]=d+"="+encodeURIComponent(b[c][d]);return a.join("&")},l=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(l()){this.startTime=
(new Date).getTime();var c=a,f=new Image,r=c.indexOf("?")!=-1?"&":"?",h=_mrmcp.title||window._mrmma_title,k=+new Date,q=window.location.host,p=(_mrmcp.width||window._mrmma_width)+"x"+(_mrmcp.height||window._mrmma_height),m=window.location.href.slice(window.location.href.indexOf("/",8)),y=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=q;b.mscs=p;b.msp=m;b.mssr=y;b.mssi=genSessionId(16);b.mscn=h;b.msct=k;b.crid=_mrmcp.creative_id||"";for(var z in b)b.hasOwnProperty(z)&&(this.setCustomVar(d,
z,b[z]),d++);b=e("msuid");if(!b)h=b=genSessionId(32),k=new Date,q=window.location.host.split("."),p=q.length,m="",m=p>=2?"."+q[p-2]+"."+q[p-1]:".mugeda.com",k.setDate(k.getDate()+3650),document.cookie="msuid="+escape(h)+(3650==null?"":";expires="+k.toGMTString())+"; domain="+m+"; path=/";this.setCustomVar(d++,"msuid",b);b=g();f.src=c+r+("mst=1&"+b)}};this.trackEvent=function(a){if(l()){var b=new Image,e=c,d=e.indexOf("?")!=-1?"&":"?",f=g(),a=a||{},k=(new Date).getTime(),q=k-this.startTime,p=encodeURIComponent(a.action||
"submit"),m=encodeURIComponent(a.categroy||"weika"),y=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=e+d+f+"&mst=2&msts="+k+"&msetd="+q+"&msen="+p+"&msev="+a+"&msec="+m+"&msel="+y}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$24){}
function createFontFaceStyle(a,c,b,d,f,e){var g="cloudfont-"+c;b&&(g+="-"+b);var l=document.getElementById(g),j=Object.prototype.toString.call(d)==="[object Array]"&&typeof f==="function",i=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif':b&&(a+="-"+b);if(l)return j&&(c=l.textContent.match(/src:url\((.*?)\)/),f(a,c?c[1]:null)),a;else if(e)return null;for(var e=(e=i("fontApiType"))?
e:3,l=d||["eot","eot","woff","ttf","svg"],t=c.indexOf("?")>-1?"&":"?",i=window.bd_version||i("v")||0,r=[],h=d&&d.length,k=d=0,q=function(a,c){var e=document.querySelector(".cloudfont_"+b);e&&document.head.removeChild(e);var d=document.createElement("style"),f,h=function(a){d.id=g;d.className="cloudfont_"+b;a=document.createTextNode(a);d.type="text/css";d.appendChild(a);document.head.appendChild(d)};if(c){var j,i=new window.FileReader;i.readAsDataURL(c);i.onloadend=function(){j=i.result;f="@font-face {font-family:'"+
a+"';\nsrc:url("+j+");}";h(f)}}else f="@font-face {font-family:'"+a+"';\nsrc:"+r[0]+";\nsrc:"+r.slice(1).join(",\n")+";}",h(f)},p=function(b){ajaxHelper({url:b,cache_ok:true,type:"data",success:function(b){++k===h&&typeof f==="function"&&(q(a,b),f(a,b))},error:function(a){a.status==414&&Mugeda.messageBox(Lang.M_TextTooLong);if(--h===0)throw f(false),"request font failed";}})},m=0,y=l.length;m<y;m++){var z=c+t+"format="+l[m]+"&api_type="+e+"&v="+i,B="url("+z+")";if(m>0){var n=l[m];l[m]==="eot"?n="embedded-opentype":
l[m]==="ttf"&&(n="truetype");B+=" format('"+n+"')"}r.push(B);j&&(d++,p(z))}if(j){if(d===0)throw"request type invalid";}else q(a);return a}
Mugeda.messageBox=function(a,c,b){var d=document.createElement("div");d.id="message_holder_"+(new Date).getTime();d.style.display="block";d.style.position="absolute";d.style.left=0;d.style.top=0;d.style.width="100%";d.style.height="100%";d.style.zIndex=2E5;var f=document.createElement("div");f.className="messageMask";f.style.display="block";f.style.position="absolute";f.style.left=0;f.style.top=0;f.style.width="100%";f.style.height="100%";f.style.backgroundColor="rgba(0,0,0,0.5)";d.appendChild(f);
var c=c||"alert",e=document.createElement("div");e.className="messageInfo";e.style.display="block";e.style.position="absolute";e.innerHTML='<div class="messageBody">'+a+'</div><div align="center" class="messageConfirm '+c+'" onclick="onConfirmMessage();">\u786e\u8ba4</div><div align="center" class="messageCancel '+c+'" onclick="onCancelMessage();">\u53d6\u6d88</div>';d.appendChild(e);document.body.appendChild(d);d.querySelector(".messageConfirm").onclick=function(){document.body.removeChild(d);b&&
b(true)};d.querySelector(".messageCancel").onclick=function(){document.body.removeChild(d);b&&b(false)};d.querySelector(".messageMask").onclick=function(){e.className="messageInfo blinking";setTimeout(function(){e.className="messageInfo"},800)};a=document.getElementById("mugeda_message_styles");if(!a)a=document.createElement("style"),a.type="text/css",a.id="mugeda_message_styles",a.innerHTML=".messageBody { padding:32px; background-color: #fff; border-top-left-radius: 4px; border-top-right-radius: 4px; }.messageInfo { max-width: 512px; min-width: 256px; margin-left:50%; transform: translate(-50%, -50%); margin-top: 256px; font-size:14px; border: 4px solid rgba(0,0,0,0); border-radius:8px; line-height: 20px; }.messageConfirm, .messageCancel { width: 50%; display: inline-block; height: 48px; line-height: 48px; color: #fff; cursor: pointer; }.messageConfirm.alert { width: 100%; }.messageCancel.alert { display: none;}.messageCancel:active, .messageConfirm:active {-webkit-filter: brightness(115%);}.messageConfirm { background-color: #F36523; border-bottom-left-radius: 4px;}.messageInfo.blinking{ -webkit-animation: blinking 200ms infinite step-end; animation: blinking 200ms infinite step-end; }@-webkit-keyframes blinking {0% {border-color: rgba(255,0,0,0);} 50% {border-color: rgba(255,0,0,0.6);}}@keyframes blinking {0% { border-color: rgba(255,0,0,0);} 50% { border-color: rgba(255,0,0,0.6);}}.messageCancel { background-color: #999; border-bottom-right-radius: 4px;}",
document.body.appendChild(a)};
