MugedaHelper={};function G(a){return document.getElementById(a)}function E(a,d,b){d||(d="load");b||(b=window);b.attachEvent?b.attachEvent("on"+d,a):b.addEventListener(d,a,false)}function json(a){try{return eval("("+a+")")}catch(d){return null}}function _85(a){if(!a||typeof a=="string")return a;var d="",b;for(b in a)d+="&"+b+"="+encodeURIComponent(a[b]);d&&(d=d.substr(1));return d}
function ajax(a){var d=/POST/i.test(a.type),b=a.data||"",c=a.dataType,f=a.url||location.href,e=/\?/.test(f)?"&":"?",g=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP")||new ActiveXObject("Microsoft.XMLHTTP");g.onreadystatechange=function(b){if(g.readyState==4)g.status==200?(b=g.responseText,c=="json"&&(b=json(b)),(d=a.success)&&d(b)):a.error&&a.error(g.status,g)};if(typeof b=="object"){var i=[],h;for(h in b)i.push(encodeURIComponent(h)+"="+encodeURIComponent(b[h]));b=i.join("&")}g.open(d?
"POST":"GET",f+(d?"":(b?e:"")+b+(a.cache?"":(!b&&e=="?"?"?":"&")+"_="+(new Date).getTime())),a.async===false?false:true);d&&g.setRequestHeader("Content-Type","application/x-www--urlencoded");g.send(b);return g}
var ajaxHelper=function(a){a=a||{};a.method=a.method||"GET";a.type=(a.type||"text").toLowerCase();a.jsonp_callback=a.jsonp_callback||"callback";a.success=a.success||function(){};a.error=a.error||function(){};a.cache_ok=a.cache_ok||false;a.url=a.url||(a.error({status:-5,desc:"Empty url"}),"");a.cache_ok||(a.url+=a.url.indexOf("?")>-1?"&":"?",a.url+="_mats="+(new Date).getTime(),a.url+="&callback="+a.jsonp_callback);if(a.type=="jsonp"){window[a.jsonp_callback]=function(b){a.success(b)};var d=document.getElementsByTagName("head")[0],
b=document.createElement("script");b.type="text/javascript";b.src=a.url;b.onload=function(){};b.onerror=function(){a.error({status:-2,desc:"Failed to load the url: "+a.url})};d.appendChild(b)}else{var c;window.XMLHttpRequest?c=new XMLHttpRequest:a.error({status:-3,desc:"Platform not supported"});c.onreadystatechange=function(){if(c.readyState==4)if(c.status==200){var b="ok",b=c.responseText;if(a.type=="json")try{b=JSON.parse(b),a.success(b)}catch(d){b=d.toString(),a.error({status:-6,desc:"Error in parsing JSON ("+
b+")"})}else a.type=="text"&&a.success(b)}else a.error({status:-4,desc:"Error in fetching data (code "+c.status+")"})};c.open(a.method,a.url,true);c.send()}};function isMobile(){return navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)?true:false}
function fo(a){var d=0,b=0;do d+=a.offsetLeft||0,b+=a.offsetTop||0;while(a=a.offsetParent);return{x:d,y:b}}function fe(a){a=a||event;return{x:a.pageX||a.x,y:a.pageY||a.y}}function fc(a){a&&a.stopPropagation?a.stopPropagation():event.cancelBubble=true}function getClass(a,d){for(var b=RegExp("(^|\\s*)"+a+"(\\s*|$)"),c=d?document.getElementsByTagName(d):document.getElementsByTagName("*")||document.all,f=[],e=0,g=c.length;e<g;e++)b.test(c[e].className)&&f.push(c[e]);return f}JSON.clone=function(a){return JSON.parse(JSON.stringify(a))};
function getElementOffset(a){for(var d=0,b=0;a&&a.tagName!="BODY";)d+=a.offsetTop,b+=a.offsetLeft,a=a.offsetParent;return{top:d,left:b}}
MugedaMraid={mraidReadyStatus:0,mraidState:void 0,getStage:function(){var a=null;for(window.event&&(a=window.event.target||window.event.srcElement);a;){if((a.id||"").indexOf("_stage")>0||a.getAttribute&&a.getAttribute("data-mid")==0)break;a=a.parentNode}return a?a:document.getElementsByClassName("MugedaStage")[0]},setMraidState:function(a){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var d=_mrmcp.display_mode,b=mraid.getPlacementType();this.mraidState=a.toLowerCase();var c=document.getElementById("mugeda_close_button");
switch(this.mraidState){case "default":if(d!="expand"&&b!="interstitial"&&c)c.style.display="none";typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(1);break;case "expanded":(d=="auto"||d=="expand"||d=="interstitial")&&setTimeout(function(){c.style.display="block"},50);break;case "resized":setTimeout(function(){c.style.display="block"},50)}},openLink:function(a,d){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;_mrmcp.destination_url&&_mrmcp.destination_url.indexOf("%DESTURL%")<0&&(a=
_mrmcp.destination_url);var b="ts="+(new Date).getTime();b+="&_moid="+(_mrmcp.owner_id||"");b+="&_mcid="+(_mrmcp.creative_id||"");b+="&_mw="+(_mrmcp.width||"");b+="&_mh="+(_mrmcp.height||"");b+="&_mtp="+(_mrmcp.type||"");b+="&_mtt="+encodeURIComponent(_mrmcp.title||"");var c=_mrmcp.custom_params;c&&c.indexOf("%CUSTOMPARAM%")<0&&(b+="&"+c);if((c=_mrmcp.redirect_url)&&c.indexOf("%LINK%")<0)var f=a.indexOf("?"),e=f<0?"?":"&",a=c+(c.lastIndexOf("=")==c.length-1?encodeURIComponent(a+e+b):"");e=a.split("#");
c="";e.length>1&&(c=e[1],a=e[0]);var f=a.indexOf("?"),e=f<0?"?":"&",f=f==a.length-1,g=window.location.search;if(g){for(var g=g.split("?")[1],i=g.split("&"),h=i.length,j=0;j<h;j++){var t=i[j].split("=");if(t.length==2){var p=t[1];t[0].toLowerCase()=="mugeda_click_link"&&(a=unescape(p),f=a.indexOf("?"),e=a<0?"?":"&",f=f==a.length-1)}}a+=(f?"":e)+g;f=false;g.length&&(e="&")}a+=(f?"":e)+b+(c?"#"+c:"");this.mraidReadyStatus==1?d=="internal"?mraid.open(a):d=="expand"?this.expand(a,0):window.open(a):d==
"internal"?window.location=a:d=="expand"?this.expand(a):window.open(a);MugedaTracker.fireEvent({category:"link",action:d,label:a,value:0})},expand:function(a,d,b){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;if(this.mraidReadyStatus!=1){if(a&&a.length){var c=document.URL.match(/client.*preview.*id/),f=b=null;try{b=(c?window:window.parent).document,f=b.getElementById("mugeda_expanded")||b.createElement("div")}catch(e){window.open(a);return}a.match(/^(\/|http:|https:)/i)||(a=(_mrmcp.creative_path||"")+
a);f.id="mugeda_expanded";f.style.display="block";f.style.position="fixed";f.style.width=(b.defaultView.innerWidth||b.documentElement.clientWidth)+"px";f.style.height=(b.defaultView.innerHeight||b.defaultView.innerHeight)+"px";f.style.left="0px";f.style.margin="0";f.style.padding="0";f.style.border="none";f.style.top="0px";f.style.background="#000";f.innerHTML="<iframe id='mugeda_expand_iframe' src='"+a+"' style='border:none;width:100%;height:100%;margin:0px;padding:0px;z-index:9999999'></iframe>";b.body.appendChild(f);
MugedaBehavior.processCloseButton("expand",b)}}else{var b=b||{},f=mraid.getMaxSize(),c=parseInt(b.width)||f.width,f=parseInt(b.height)||f.height,a=a||b.url,g=!a||a.length==0;d==1?(a=parseInt(b.left)||0,b=parseInt(b.top)||0,MugedaBehavior.processCloseButton("resize"),mraid.setResizeProperties({width:c,height:f,offsetX:a,offsetY:b,allowOffscreen:false}),mraid.resize()):(mraid.setExpandProperties({width:c,height:f,isModal:true,useCustomClose:_mrmcp.display_mode?true:false}),g?(mraid.expand(),MugedaBehavior.processCloseButton()):
mraid.expand(a))}},sendEmail:function(a){window.open("mailto:"+a.email_addr+"?subject="+a.email_title+"&body="+a.email_body,"_self")},savePicture:function(a){this.mraidReadyStatus==1&&mraid.supports("storePicture")&&mraid.storePicture(a.url)},addCalendarEvent:function(a){this.mraidReadyStatus==1&&mraid.supports("calendar")&&mraid.createCalendarEvent({summary:a.calendar_summary,description:a.calendar_desc,location:a.calendar_location,start:a.calendar_start_time,end:a.calendar_end_time})},createHTML5VideoTag:function(a,
d){if(a){var b="_"+ +new Date,c=0,f=0;a.data&&(b="_"+a.data.guid,a.data.param&&(c=a.data.param.continueAudio||0,f=a.data.param.clickStatus||0));var e=G("mugeda_video"+b);if(e)return e.parentNode;div=document.createElement("div");div.className="mugedaVideoHolder";div.style.margin=0;div.style.padding=0;div.style.backgroundColor="rgba(0,0,0,0.8)";div.style.position="absolute";div.style.top=0;div.style.left=0;div.style.width=0;div.style.height=0;div.style.zIndex=1;div.style.display="none";_mrmcp=typeof _mrmcp==
"undefined"?{}:_mrmcp;var g=(_mrmcp.creative_path||"")+"close_button.png",i=navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i);div.innerHTML='<video id="mugeda_video'+b+'" preload="auto" webkit-playsinline="true" video-id="'+d.id+'"  video-mode="'+d.mode+'" video-name="'+d.name+'"  style="width:100%;height:100%;position:absolute;z-index:2;"></video>'+('<div id="mugeda_video_close'+b+'" align="middle" style="position: absolute;color:white;width:36px;height:36px;right:0px;top: '+
(i?0:0)+"px;cursor:pointer;background-image: url("+g+');z-index:3;"></div>');a.appendChild?a.appendChild(div):a.dom&&a.dom.appendChild(div);e=G("mugeda_video"+b);b=G("mugeda_video_close"+b);b.style.display=d.close_button?"block":"none";d.close_button&&(g=isMobile()?"touchend":"click",b.addEventListener(g,function(a){a.stopPropagation();e.src="";e.rawSrc="";e.load();div.style.display="none"},false));d.video_controls?e.setAttribute("controls","controls"):e.removeAttribute("controls");e.rawPlay=e.play;
e.rawPause=e.pause;e.play=function(){e.paused&&(e.onplayed(),e.rawPlay())};e.pause=function(){e.onpaused();e.rawPause()};e.onplayed=function(){if(c==0&&window.backgroundMusic)backgroundMusic.prevPlayStatus=backgroundMusic.playStatus,backgroundMusic.pause(),backgroundMusic.playStatus=0};e.onpaused=function(){if(c==0&&window.backgroundMusic&&backgroundMusic.prevPlayStatus==1)backgroundMusic.play(),backgroundMusic.playStatus=1,delete backgroundMusic.prevPlayStatus};e.onclick=function(a){a.preventDefault();
a.stopPropagation();f===0?this.paused?this.play():this.pause():this.paused&&this.play()};return div}},loadUrl:function(a){var d=a.id||(new Date).getTime(),b=a.url||"",c=a.left||0,f=a.top||0,e=isNaN(a.width)?window.aniData?window.aniData.width:320:Math.max(0,a.width),g=isNaN(a.height)?window.aniData?window.aniData.height:240:Math.max(0,a.height),i=a.before||null,h=a.style,j=a.scroll,t=a.parent,p=a.onload,l=a.onclose,o=a.position,q=a.close_position;if(!i&&!t){var u=typeof Mugeda!="undefined"&&Mugeda.getCanvas?
Mugeda.getCanvas():this.getStage();typeof Mugeda!="undefined"&&u&&(u=getElementOffset(u),c+=u.left,f+=u.top)}var n=G(d);n||(n=document.createElement("div"),t?t.appendChild(n):i?i.parentNode.insertBefore(n,i):document.body.appendChild(n));n.id=d;n.style.margin=0;n.style.padding=0;n.style.backgroundColor="transparent";n.style.position=o?o:"fixed";n.style.top=0;n.style.left=0;n.style.width=0;n.style.height=0;switch(q){case "leftTop":q="left:4px;top:4px;";break;case "leftbottom":q="left:4px;bottom:4px;";
break;case "rightbottom":q="right:4px;bottom:4px;";break;default:q="right: 4px;top: 4px;"}n.innerHTML="<iframe "+(j?"":"scrolling=no ")+'id="'+d+'_iframe" style="border:none; width:100%;height:100%; '+(j?"":"overflow:hidden;")+' " ></iframe>'+('<div id="'+d+'_iframe_close" align="middle" style="position: absolute;color:white;width: 24px;height: 24px; '+q+'cursor:pointer;background: rgba(0,0,0,0.5);border: 3px solid white;border-radius: 15px;font-family:arial;font-size: 16px;line-height:24px;">&#10006;</div>');
n.style.display="none";n.style.top=f+"px";n.style.left=c+"px";n.style.width=e+"px";n.style.height=g+"px";n.style.display="block";n.style.cssText+=h;G(d+"_iframe_close").style.display=a.close_button?"block":"none";setTimeout(function(){if(a.close_button)G(d+"_iframe_close").onclick=function(){n.style.display="none";G(d+"_iframe").src="about:blank";l&&l(n)}},100);setTimeout(function(){var a=G(d+"_iframe");a.src=b;if(p)try{a.onload=function(){p(a);a.onload=null}}catch(c){}},100);return n},playAudio:function(a,
d){var b=false;if(!a||!a.audio_url||!a.audio_url.length)return false;var c=typeof Mugeda!="undefined"&&Mugeda.getAudioCache?Mugeda.getAudioCache(a.audio_url,a.audioId):MugedaBehavior.localCache[a.audio_url];if(c){if(c.loop=parseInt(a.audio_loop)==1?true:false,c.play)if(c.webAudio)b=c.play(a.event=="click"||d?true:false);else if(a.event=="click"){try{c.pause(),c.currentTime=0}catch(f){}setTimeout(function(){c.play()},5)}else(c.playStatus!=1||d)&&setTimeout(function(){c.play();c.playStatus=1;b=true},
10)}else{var c=new Audio,e=document.createElement("source"),g=a.audio_url.lastIndexOf("."),g=a.audio_url.substring(g+1),i=true;switch(g){case "ogg":e.type="audio/ogg";break;case "mp3":e.type="audio/mpeg";break;default:i=false,console.log("Audio extension ("+g+") not supported.")}if(i){e.src=a.audio_url;c.appendChild(e);c.autoplay=false;c.preload="auto";c.load();var h=document.getElementById("mugeda_resource_loading");if(!h)h=document.createElement("img"),h.id="mugeda_resource_loading",h.style.position=
"fixed",h.style.right="2px",h.style.top="2px",h.style.display="block",h.src=(_mrmcp.creative_path||"")+"loading.gif",document.body.appendChild(h);h.style.display="block";b=true;c.addEventListener("canplay",function(){h.style.display="none";c.play()},false);MugedaBehavior.localCache[a.audio_url]=c}}return b},playHTML5Video:function(a){var d=a.left||0,b=a.top||0,c=isNaN(a.width)?"100%":Math.max(0,a.width)+"px",f=isNaN(a.height)?"100%":Math.max(0,a.height)+"px",e=window.Mugeda&&Mugeda.getCanvas?Mugeda.getCanvas():
this.getStage();typeof Mugeda!="undefined"&&e&&!a.video_holder&&!isNaN(a.left)&&(e=getElementOffset(e),d+=e.left,b+=e.top);var g=document.body;if(a.video_holder)if((e=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&e.scene){var g=a.video_holder,g=g.split("/"),i=a.video_object===1;if(g.length===2)e=e.scene.getObjectByName(i?g[1]:g[0]),i?(g=e?e.scene.objectHash[g[0]]:null,a.url=g?g.data.param.videoUrl:a.url):g=e?e.scene.getObjectByName(g[1]):null;else if(i){if((g=e.scene.objectHash[a.video_holder])||
(g=e.scene.dom.querySelector('*[data-guid="'+a.video_holder+'"]')),g&&g.data)a.url=g.data.param.videoUrl}else g=e.scene.getObjectByName(a.video_holder)}else{if(window.mugedaCss&&mugedaCss.magic&&(e=document.getElementById(mugedaCss.magic+"stage")))g=a.video_holder,g=g.split("/").map(function(a){return"."+a}),(g=e.querySelectorAll(g.join(" ")))&&g.length&&(g=g[0])}else g=document.body;e=this.createHTML5VideoTag(g,a);e.style.top=b+"px";e.style.left=d+"px";e.style.width=c;e.style.height=f;e.style.display=
"block";var h=e.querySelector("video");h.src=a.url;h.rawSrc=a.url;h.load();setTimeout(function(){h.play();h.playing=true},10)},playVideo:function(a){a=a||{};if(!a.video_url)return false;if(this.mraidReadyStatus!=1){var d=a.dom||document.querySelector('video[video-id="'+a.video_id+'"]');a.video_mode=="object"&&a.video_id&&d&&d.rawSrc==a.video_url||this.playHTML5Video({url:a.video_url,id:a.video_id||"",name:a.video_name||"",mode:a.video_mode||"",video_object:parseInt(a.video_object,10),video_holder:a.video_holder,
left:parseInt(a.video_left,10),top:parseInt(a.video_top,10),width:parseInt(a.video_width,10),height:parseInt(a.video_height,10),close_button:parseInt(a.video_close,10)==1,video_controls:parseInt(a.video_controls,10)==1,auto:parseInt(a.video_autoplay,10)==1})}else mraid.playVideo(a.video_url)},stopVideo:function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),d=0,b=a.length;d<b;d++){var c=a[d].querySelector("video");if(c)c.src="",c.rawSrc="",c.load();a[d]&&(a[d].style.display="none")}},
controlVideo:function(a,d){var b=document.querySelector("#mugeda_video_"+a);if(b)if(d=="play")b.play();else if(d=="pause")b.pause();else{if(d=="stop")b.pause(),b.currentTime=0}else if((b=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&b.scene)if(b=b.scene.objectHash[a]){var c=b.data.param;d==="play"&&MugedaMraid.playVideo({auto:c.videoAutoPlay,clickStatus:c.clickStatus,event_name:"",hidePlayIcon:c.hidePlayIcon,video_close:0,video_continue_audio:c.continueAudio,video_controls:c.hidePlayControls==
1?0:1,video_holder:b.data.guid,video_left:0,video_mode:"object",video_name:c.name,video_object:1,video_top:0,video_url:c.videoUrl})}},sendShortMessage:function(a){window.open("sms:"+a.phone_number+"?body="+a.sms_body,"_self")},makePhoneCall:function(a){window.open("tel:"+a.phone_number,"_self")}};
MugedaBehavior={localCache:{},shakeHash:{},pause:function(){typeof Mugeda!="undefined"&&Mugeda.pause&&Mugeda.pause()},resume:function(a){typeof Mugeda!="undefined"&&Mugeda.resume&&Mugeda.resume(a)},nextPage:function(){typeof Mugeda!="undefined"&&Mugeda.nextPage&&Mugeda.nextPage()},prevPage:function(){typeof Mugeda!="undefined"&&Mugeda.prevPage&&Mugeda.prevPage()},gotoPage:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoPage&&Mugeda.gotoPage(a)},disablePage:function(){typeof Mugeda!="undefined"&&
Mugeda.disablePage&&Mugeda.disablePage()},enablePage:function(){typeof Mugeda!="undefined"&&Mugeda.enablePage&&Mugeda.enablePage()},next:function(){typeof Mugeda!="undefined"&&Mugeda.next&&Mugeda.next()},previous:function(){typeof Mugeda!="undefined"&&Mugeda.previous&&Mugeda.previous()},gotoAndPlay:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPlay&&Mugeda.gotoAndPlay(a)},gotoAndStop:function(a){gotoAndPause(a)},gotoAndPause:function(a){typeof Mugeda!="undefined"&&Mugeda.gotoAndPause&&Mugeda.gotoAndPause(a)},
callback:function(a,d){if(window&&d.name&&d.name.length&&window[d.name])window[d.name](a,d.key,d.value)},map:function(a){var d=a.map_key.replace(/(\n|\r)/g,"+"),b=a.map_address.replace(/(\n|\r)/g,"+"),c=navigator.userAgent.toLowerCase().indexOf("android")>-1,f=parseInt(a.map_type,10),e=function(){for(var a=document.querySelectorAll("div.mugedaVideoHolder"),b=0,d=a.length;b<d;b++)a[b]&&(a[b].style.display="none");(a=G("mugedaMap-mask"))?g(1):(a=document.createElement("div"),b=window._mrmcp&&_mrmcp.creative_path?
_mrmcp.creative_path+"loading.gif":"/images/loading.gif",a.id="mugedaMap-mask",a.className="mugedaMapControl",a.innerHTML='<p id="mugedaMap-title"><a id="mugedaMap-back">\u8fd4\u56de</a>\u4f4d\u7f6e\u4fe1\u606f</p><div id="mugedaMap-con"></div><div id="mugedaMap-loading"><div class="spinner"></div><style>.mugedaMapControl {position:absolute;left:0;top:0;height:100%;width:100%;z-index:999999;}.mugedaMapMaskVisible {-webkit-transition:transform 1s;transform:translate3d(-100%, 0, 0);-webkit-transform:translate3d(-100%, 0, 0);}.mugedaMapControl #mugedaMap-title {position:fixed;height:44px;line-height:44px;width:100%;text-align:center;z-index:1;background:rgba(255,255,255,.8);margin:0;}.mugedaMapControl #mugedaMap-con {height:100%;width:100%;}.mugedaMapControl #mugedaMap-back {position:absolute;left:5px;display:inline-block;height:100%;width:40px;cursor:pointer;}.mugedaMapControl #mugedaMap-loading {position:absolute;width:100%;height:100%;line-height:100%;left:0;top:44px;display:none;background:#fff;z-index:2;}.mugedaMapControl .spinner {position:absolute;width:20px;height:30px;left:50%;top:50%;margin:-50px 0 0 -10px;background-image:url('+
b+');background-repeat:no-repeat;background-size:contain;}.mugedaMapControl .spinner:after {content: "\u52a0\u8f7d\u4e2d ...";position:absolute;width:80px;left:-25px;top:120%;}</style>',document.body.appendChild(a),(a=G("mugedaMap-back"))&&a.addEventListener("click",function(a){a.stopPropagation();g(0)},false))},g=function(a){var b=G("mugedaMap-mask");b&&b.classList.toggle("mugedaMapMaskVisible",!a)},i=function(a){var b=G("mugedaMap-loading");if(b)b.style.display=a?"block":"none"},h,j,t=function(a,
b,d,c){h||(h=new BMap.Map("mugedaMap-con"));h.centerAndZoom(d||"\u5317\u4eac",11);h.addControl(new BMap.ZoomControl);j||(j=new BMap.LocalSearch(h,{renderOptions:{map:h,autoViewport:true},onSearchComplete:function(a){typeof c==="function"&&c.call(h,a)}}));b&&a?j.searchNearby(b,a):j.search(b)},p=function(a,b,d){if(f===0){var c=["http://api.map.baidu.com/getscript?type=quick&file=api&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0","http://api.map.baidu.com/getscript?type=quick&file=feature&ak=FOm6cLbES9zjrtvcDYndkwSR&v=1.0"],
b=decodeURIComponent(b),a=decodeURIComponent(a);e();i(1);for(var h=0,d=0,g=c.length;d<g;d++){var j=document.createElement("script");j.src=c[d];j.onload=function(){++h===g&&t(a,b,"",function(a){a.getNumPois()===0&&alert("\u62b1\u6b49\uff0c\u6ca1\u6709\u641c\u7d22\u5230\u76f8\u5173\u4fe1\u606f");i(0)})};document.head.appendChild(j)}}else if(c="https://maps.google.com/maps?q="+(a+""+(b.length?"+near+"+b:""))+"&z=12",j=parseFloat((""+(/CPU.*OS ([0-9_]{1,5})|(CPU like).*AppleWebKit.*Mobile/i.exec(navigator.userAgent)||
[0,""])[1]).replace("undefined","3_2").replace("_",".").replace("_",""))||false,d==1){if(d=document.getElementById("aMugedaGeoLocation"))d.href=c,c=document.createEvent("HTMLEvents"),c.initEvent("click",true,true),d.dispatchEvent(c)}else j&&j<6?window.location.href=c:window.open(c,"_blank")};if(!c&&b.length==0&&navigator.geolocation){a=document.getElementById("aMugedaGeoLocation");if(!a)a=document.createElement("a"),a.id="aMugedaGeoLocation",a.style.display="none",a.href="",a.target="_blank",document.body.appendChild(a);
navigator.geolocation.getCurrentPosition(function(a){b=a.coords.latitude+","+a.coords.longitude;p(d,b,1)})}else p(d,b)},popupForm:function(a,d){function b(a,b){if(a&&b)return a.querySelector("#"+b)}function c(a){if(window.localStorage&&window.localStorage.getItem)return unescape(localStorage.getItem(a)||"");var b,d,c,e=document.cookie.split(";");for(b=0;b<e.length;b++)if(d=e[b].substr(0,e[b].indexOf("=")),c=e[b].substr(e[b].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,""),d==a.toLowerCase())return unescape(c);
return""}function f(a,b){if(window.localStorage&&window.localStorage.getItem)try{localStorage.setItem(a,escape(b))}catch(d){console.info("Oops, localStorage full"),localStorage.clear(),localStorage.setItem(a,escape(b))}else{var c=new Date;c.setDate(c.getDate()+3);c=escape(b)+"; expires="+c.toUTCString();document.cookie=a.toLowerCase()+"="+c}}function e(a){var b=document.querySelector(".MugedaStage")?null:G("viewbox")||G("frame");if(b)b.style.display=a?"":"none";return b?true:false}function g(a){if(d){var b=
function(a,b){Array.prototype.forEach.call(a,function(a,d){b(a,d)})};b(a.querySelectorAll(".popupFormInputBox input,.popupFormInputBox textarea"),function(a){a.value=""});b(a.querySelectorAll(".popupFormRadioList input,.popupFormCheckbox input"),function(a){a.checked=false});b(a.querySelectorAll(".popupFormSelectList select"),function(a){a.value=a.querySelector("option").getAttribute("value")})}else if(b=a.querySelector("form"),b.style.bottom=-b.offsetHeight+"px",a.style.background="rgba(0,0,0,0)",
setTimeout(function(){a.parentNode&&a.parentNode.removeChild(a)},500),e(1)&&(document.body.style.overflowY="hidden",isMobile()))document.body.style.height="100%"}var i=a.openTarget=="default"||a.openTarget=="frame"||a.openTarget=="page";if(a&&!(a.openTarget=="callback"&&!a.callback||a.openTarget!="callback"&&a.openTarget!="customizable"&&!i&&!a.url)){var i=document.documentElement.clientWidth,h=document.documentElement.clientHeight,j=[],t=function(b,d){var d=d||{},c=d.detail,e=d.form||(c?c.form:null),
c={item:c,form:e,title:a.title,hideItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="none")},showItem:function(a){e&&e.elements[a]&&(e.elements[a].parentNode.style.display="block")}},d=document.createEvent("Events");d.initEvent(b,true,true);d.detail=c;window.dispatchEvent(d)};window.addEventListener("_mugedaFormChanged",function(a){t("mugedaFormChanged",a)});var p=a.items||[];window.popupFormFields=p;if(!a.html){var l="";d?(l+='<div class="popupFormContent">',a.title&&(l+=
'<div align="center" class="popupFormTitle"><h2>'+a.title+"</h2></div>")):(l+='<div align="center" class="popupFormTitle">',l+='<div class="title-col-2" align="center"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel"></div>',l+='<div class="title-col-6" align="center"><h2>'+(a.title||"&nbsp;")+"</h2></div>",l+='<div class="title-col-2" align="center"><input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>',l+="</div>",
l+='<div class="popupFormContent">');var o=navigator.userAgent.toLowerCase(),q=o.indexOf("android")>-1,u=parseFloat(o.slice(o.indexOf("android")+8)),n="",v=0,A={phone:"tel",input:"text"};q&&u<3&&(n="-webkit-transform: scale(2,2);-webkit-transform-origin:center center;");for(var B=d?"":":",o=0;o<p.length;o++){var k=p[o],y=(k.value||"").trim();if(y){for(var y=y.split("\n"),r=[],w=0;w<y.length;w++){var I=y[w].split("("),z=I[0],I=(I[1]||"").replace(/\)$/,"")||z,F=["FORMID",I,o,w].join("_");r[w]={id:F,
text:z,value:I}}y=r}F='id="popupFormField_'+o+'"';switch(k.type){case "radio":l+="<div "+F+' class="popupFormRadioList">';k.description&&(l+='<label class="inputlabel">'+k.description+(k.required?"*":"")+B+"</label>");l+='<div class="mformradio">';for(w=0;w<y.length;w++)r=y[w],z=c(r.id),l+='<label><input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="radio" name="'+k.id+'" value="'+
r.value+'" id="'+r.id+'" '+(z=="true"?"checked=checked":"")+" ><span "+(w==y.length-1?"":" style='border-right:1px solid "+a.background+"'")+">"+r.text+"</span></label>",j[r.id]=r.id;l+="</div></div>";break;case "checkbox":l+="<div "+F+' class="popupFormCheckbox">';k.description&&(l+='<label class="inputlabel">'+k.description+(k.required?"*":"")+B+"</label>");l+='<div class="mformcheck">';l+=k.rangeType==="vertical"?"<table>":"";for(w=0;w<y.length;w++)r=y[w],z=c(r.id),l+=k.rangeType==="vertical"?
'<tr><td><input type="checkbox" value="'+r.value+'" id="'+r.id+'" '+(z=="true"?"checked=true":"")+' ></td><td><label for="'+r.id+'" >'+r.text+"</label></td></tr>":'<input onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" type="checkbox" name="'+k.id+'" value="'+r.value+'" id="'+r.id+'" '+(z=="true"?"checked=true":"")+' ><label for="'+r.id+'" >'+r.text+"</label>",j[r.id]=r.id;q&&u<3&&k.rangeType!=
"vertical"&&(v=6);l+=k.rangeType==="vertical"?"</table>":"";l+="</div></div>";break;case "select":l+="<div "+F+' class="popupFormSelectList">';k.description&&(l+='<label class="inputlabel text">'+k.description+(k.required?"*":"")+B+"</label>");l+='<select class="text" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" name="'+k.id+'" id="'+("_map_"+k.description)+'">';l+='<option value="">'+k.description+
"</option>";z=c(k.description);for(w=0;w<y.length;w++)r=y[w],l+='<option value="'+r.value+'" '+(z==r.value?"selected=selected":"")+">"+r.text+"</option>";l+="</select>";l+="</div>";j[k.description]="_map_"+k.description;break;case "textarea":l+="<div "+F+' class="popupFormInputBox">';l+='<label class="inputlabel inputlabel_area">'+k.description+(k.required?"*":"")+B+'</label><textarea name="'+k.id+'" id="_mcp_'+escape(k.description)+'" rows="4" onchange="var event = document.createEvent(\'Events\');event.initEvent(\'_mugedaFormChanged\', true, true);event.detail = this;window.dispatchEvent(event);" style="resize:none; height:48px;">'+
(k.value.length?k.value:c(k.description))+"</textarea>";l+="</div>";j[k.description]="_mcp_"+escape(k.description);break;default:l+="<div "+F+' class="popupFormInputBox">',l+='<label class="inputlabel text">'+k.description+(k.required?"*":"")+B+'</label><input class="text" name="'+k.id+'" id="_mcp_'+escape(k.description)+'" type="'+(A[k.type]||k.type)+"\" onchange=\"var event = document.createEvent('Events');event.initEvent('_mugedaFormChanged', true, true);event.detail = this;window.dispatchEvent(event);\" value=\""+
(c(k.description)||k.value)+'" '+(d?'placeholder="'+k.description+'"':"")+">",l+="</div>",j[k.description]="_mcp_"+escape(k.description)}}d&&(l+='<div class="popupFormBtn"><input type="button" value="'+a.cancelName+'" class="popupFormCancel" id="popupFormCancel">',l+='<input id="actionButton" type="button" value="'+a.submitName+'" class="popupFormSubmit"></div>');l+="</div>";a.html=l}delete this.popupFormDiv;var m=this.popupFormDiv;if(!m){o=function(b){var b=b||".popupForm",c=1;if(/^rgba\(\d+,\s\d+,\s\d+,\s([0-9.]+)\)$/.exec(a.background))c=
RegExp.$1;c="<style>"+b+" {width:100%;font-size:"+a.fontSize+'px;font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+' * {font-family:Tahoma,"\u5fae\u8f6f\u96c5\u9ed1",Arial, SimHei;}'+b+" form{position:absolute;width:100%;background-color:"+a.background+";}"+b+" *{margin:0;box-sizing:border-box;-webkit-appearance: none; -moz-appearance: none; appearance: value;}"+b+" .inputlabel{width:33%;height:28px;font-size:"+a.fontSize+"px;line-height:28px;display:inline-block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:top;color:#000;}"+
b+" span{color:#333;}"+b+" label{color:#000;}"+b+" #popupFormField_0{padding-top:16px;}"+b+" .popupFormMask {position:absolute;left:0;top:0;width:100%;height:100%;background-color: "+a.background+"}"+b+" .popupFormContent {position:relative;padding-bottom:16px; background-color:#fff;opacity:"+c+";}"+b+" .popupFormTitle {width:100%;padding:20px 0;overflow:hidden;background-color: "+a.background+"}"+b+" h2 {font-weight:normal;font-size:"+(2+parseInt(a.fontSize))+"px;color:"+a.color+";}"+b+" h3{text-align:left;font-size:"+
a.fontSize+"px; font-weight: normal;color:"+a.color+";}"+b+" .popupFormInputBox{padding:8px 16px;text-align:left;}"+b+" .popupFormInputBox input, .popupFormInputBox textarea, .popupFormSelectList select{width:67%;height:28px;border:1px solid "+a.background+";font-size:"+a.fontSize+"px;padding:0;padding-left:8px;vertical-align:top;border-radius:2px;}"+b+" .popupFormSelectList{padding:8px 16px 0;}"+b+" .popupFormRadioList{padding:8px 16px 0;}"+b+" .popupFormCheckbox{padding:8px 16px 0;}"+b+" .popupFormTitle input{border-width:0;cursor:pointer;font-size:"+
a.fontSize+"px;color:"+a.color+"}"+b+" .popupFormSubmit{border:none;background:none}"+b+" .popupFormCancel{background:none;border:none;}"+b+" .popupFormRadioList input{margin:0 5px 0 8px;}"+b+" .popupFormRadioList label{vertical-align:top;}"+b+" .mformradio {background-color:#EFEFEF;border:1px solid "+a.background+";overflow:hidden;display:inline-block;}"+b+" .mformradio label{float:left; min-width:48px;position:relative;}"+b+" .mformradio label span{text-align:center;padding:6px 8px;display:block;}"+
b+" .mformradio label input{position:absolute;width:100%;height:100%;margin:0;border:0;opacity:0;}"+b+" .mformradio input:checked + span{background-color:"+a.background+";color:#F7F7F7;}"+b+" .mformcheck{margin:0 0 8px;display:inline-block;}"+b+" .mformcheck input{"+n+"width:24px;height:24px;background-color:#EFEFEF;border:1px solid "+a.background+";vertical-align:middle;margin:3px 2px;}"+b+" .mformcheck input:checked{background-color:"+a.background+";}"+b+" .popupFormTitle .title-col-2 {float:left;width:20%;padding:0 ;text-align:center;}"+
b+" .popupFormTitle .title-col-6 {float:left;width:60%;padding:0 ;}"+b+" .popupFormTitle .title-col-2 input {font-size:"+(2+parseInt(a.fontSize))+"px;}"+b+" .mformcheck label{vertical-align:"+v+"px;font-size:"+a.fontSize+"px;padding-top:0;padding-left:4px;padding-right:8px;}";d&&(c+=b+" .popupFormBtn {width:100%;padding:20px 0 0 0;text-align:center;}",c+=b+" .popupFormSubmit {width:90px;height:30px;color:"+a.color+";background-color:"+a.background+"}",c+=b+" .popupFormCancel {width:90px;height:30px;margin-right:15px;color:"+
a.color+";display:none;background-color:"+a.background+"}");c+="</style>";return c};if(!m){var J=a.openTarget=="backend"?"popupFormIframe":"_"+a.openTarget,m=document.createElement("div");m.style.display="none";m.className=d?"popupForm2":"popupForm";var C="";if(d)var D=function(b){for(var d={l:48,r:200},c=0,e=0,f=b.length;e<f;e++){for(var h=b[e],g=h.description.length,k=0,j=0;j<g;j++)k+=h.description[j].match(/[\u3400-\u9FBF]/)?2:1;c=Math.max(c,k)}c=c>8?8:c;b=a.fontSize*(c-4);c>4&&c<=8&&(d.l+=b,d.r-=
b);return d}(p),C=o(".popupForm2");else C=o();m.innerHTML='<form method="'+a.method+'" target="'+J+'" autocomplete="on"></form><iframe name="popupFormIframe" id="popupFormIframe" style="display:none"></iframe>'+C;!d&&!a.isCss?document.body.appendChild(m):(a.hwObj=D,a.iframeDiv=m,a.parentDom&&a.parentDom.appendChild(a.iframeDiv));this.popupFormDiv=m;m.form=m.childNodes[0];m.form.onclick=function(){};self=this;d||m.addEventListener(isMobile()?"touchend":"mouseup",function(a){if(!window.cardFrame){if(a.target==
m)g(m),self.popupFormDiv=null,a.stopPropagation();var b=a.target.nodeName.toLowerCase(),d=(a.target.type||"").toLowerCase();["input","textarea","select"].indexOf(b)>=0&&d!="checkbox"&&d!="submit"&&(a.target.focus(),q&&setTimeout(function(){a.target.scrollIntoView();a.target.scrollIntoViewIfNeeded&&a.target.scrollIntoViewIfNeeded()},500),a.stopPropagation());d=="button"&&a.stopPropagation()}});C=function(){function c(){var e=[],f=p;if(!d)f=window.popupFormFields;for(var h=0;h<f.length;h++){var k=f[h],
j=b(m,"popupFormField_"+h),i="",v=j.querySelectorAll("select");v.length==0&&(v=j.querySelectorAll("textarea"),v.length==0&&(v=j.querySelectorAll("input")));if(v.length==1)i=v[0].value||"";else if(v.length>1){for(var i=[],l=0;l<v.length;l++)if(j=v[l],j.checked&&(i.push(j.value),j.type=="radio"))break;i=i.join(",")}if(k.required&&!i){alert((k.description||"item")+" required");v[0].focus();return}if(i)switch(k.type){case "phone":if(!/^\d+$/.test(i)){alert((k.description||"Phone number")+" required");
v[0].focus();return}break;case "email":if(!/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(i)){alert((k.description||"Email")+" required");v[0].focus();return}}a.openTarget==="default"?e.push(encodeURIComponent(k.description+"("+k.id+")")+"="+encodeURIComponent(i||"")):e.push(encodeURIComponent(k.id)+"="+encodeURIComponent(i||""))}if("popupFormIframe"==J)G("actionButton").value=a.pendingName;e=e.join("&");f=a.url+"?"+e;a.loadFinished=function(){g(m);self.popupFormDiv=null};if(a.openTarget=="customizable")f=
{callback:function(){a.msg&&alert(a.msg)},cancel:false},window.MugedaCard&&MugedaCard.finalizeCustomParameters&&MugedaCard.finalizeCustomParameters(e,f),f.cancel!==true&&f.callback(),a.loadFinished();else if(a.openTarget=="default"||a.openTarget=="page"||a.openTarget=="frame"||a.openTarget=="callback"){h="";f=0;if(window._mrmcp)h=window._mrmcp.creative_id||"";else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)h=Mugeda.data.crid;if(h==""&&/\/edit\/(\w+)\&?/.test(top.location.href))h=RegExp.$1,f=h.length<
16?1:2;else if(h==""&&/id=(\w+)\&?/.test(window.location.search))f=3,h=RegExp.$1;k=function(a,b,d){var d=d||"post",c=document.createElement("form"),e=document.createElement("iframe");c.setAttribute("method",d);c.setAttribute("action",a);a="__iframe"+Math.random()*1E4;e.setAttribute("id",a);e.setAttribute("name",a);c.setAttribute("target",a);e.style.width=0;e.style.height=0;e.style.display="none";e.addEventListener("load",function(){});a=0;for(d=b.length;a<d;a++){var f=b[a].split("="),h=f[0],f=f[1],
g=document.createElement("input");g.setAttribute("type","hidden");g.setAttribute("name",h);g.setAttribute("value",f);c.appendChild(g)}document.body.appendChild(c);document.body.appendChild(e);c.submit()};if(h&&/^[a-z\-]+\.mugeda\.com$/.test(window.location.hostname))window._mrmcp=window._mrmcp||{},k(_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform",(e+"&crid="+h+"&mode="+f).split("&")),a.msg&&alert(a.msg);a.openTarget=="callback"?a.callback&&window[a.callback]?(f={callback:function(){a.msg&&
alert(a.msg)},cancel:false},window[a.callback](e,f),MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",value:a.id?parseInt(a.id,36):0}),f.cancel!==true&&f.callback()):console.log("No callback function found. Skipping..."):a.openTarget=="frame"?a.callback&&a.callback():a.openTarget=="page"&&a.callback&&a.callback();a.loadFinished()}else try{window.open(f,J),G("popupFormIframe").onload=function(){a.loadFinished();MugedaTracker.fireEvent({category:"interaction",action:"form",label:"",
value:a.id?parseInt(a.id,36):0});a.msg&&alert(a.msg)}}catch(n){a.loadFinished(),alert("Form submission failed. Please try again. ")}}m.querySelector("#popupFormIframe").onload=null;for(k in j){var e=document.getElementById(j[k]);e&&(e.type=="checkbox"||e.type=="radio"?f(k,e.checked):f(k,e.value))}u<3?c():setTimeout(c,200);return false}}m.style.display="";m.form.innerHTML=a.html;if(a.id)m.form.id=a.id;var K=isMobile()?"touchstart":"click";m.form.querySelector("input[id=actionButton]").addEventListener(K,
C,false);m.style.display="";m.style.visibility="hidden";setTimeout(function(){t("mugedaFormInitialized",{form:m.form});m.style.visibility="visible"},200);setTimeout(function(){b(m,"popupFormCancel").addEventListener(K,function(){g(m);self.popupFormDiv=null},false)},500);D=m.querySelectorAll(".popupFormInput");for(o=0;o<D.length;o++)C=D[o],C.onfocus=onInputFocus,C.onblur=onInputBlur;var x;a.target?x=a.target.getBoundingClientRect():(D=Mugeda.getMugedaObject?Mugeda.getMugedaObject():null)&&a.isCss?
(i=D.adaption,x={left:Math.max(0,(window.Mugine?1:-1)*i.marginLeft),top:window.Mugine?0:Math.max(0,(window.Mugine?1:-1)*i.marginTop),width:Math.min(i.width,D.width),height:Math.min(i.height,D.height)}):x={left:0,top:0,width:i,height:h};document.body.style.overflowY="auto";if(e()){if(m.style.marginLeft=Math.max(2,x.left+document.documentElement.scrollLeft+(x.width-m.offsetWidth)/2)+"px",m.style.marginTop=Math.max(2,x.top+document.documentElement.scrollTop+(x.height-m.offsetHeight)/2)+"px",m.style.marginBottom=
"32px",m.offsetHeight+32>document.documentElement.scrollHeight&&(m.style.marginTop=parseInt(window.getComputedStyle?getComputedStyle(m).marginTop:m.currentStyle.marginTop)+32+"px",isMobile()))document.body.style.height=m.offsetHeight+64+"px"}else if(m.style.position="relative",m.style.left=x.left+"px",m.style.top=x.top+"px",Math.max(2,x.top+(x.height-m.offsetHeight)/2),Math.max(2,x.left+(x.width-m.offsetWidth)/2),!d){var H=m.querySelector("form");H.style.bottom="-9999px";m.style.overflow="hidden";
setTimeout(function(){m.style.background="rgba(0,0,0,0)";m.style.width=x.width+"px";m.style.height="100%";H.style.webkitTransition="none";H.style.bottom=-H.offsetHeight+"px";setTimeout(function(){H.style.webkitTransition="all 500ms";H.style.bottom="0px";H.style.overflowY="auto";!d&&(m.style.background="rgba(0,0,0,0.3)")},1)},1)}}}},getPopupFormHeight:function(a){for(var d=a.items,b=0,c=0,f=d.length;c<f;c++){var e=d[c];switch(e.type){case "input":case "phone":case "email":b+=44;break;case "textarea":b+=
64;break;case "radio":b+=48;break;case "checkbox":e=e.value.split("\n").length;b+=32*e+8;break;case "select":b+=36;break;default:b+=44}}a.title&&(b+=60);b+=8;b+=50;b+=16;return b},processAction:function(a,d,b){var c=true;if(a.type=="pause")this.pause(a.param);else if(a.type=="play")this.resume(1);else if(a.type=="next")this.next();else if(a.type=="previous")this.previous();else if(a.type=="nextPage")this.nextPage();else if(a.type=="prevPage")this.prevPage();else if(a.type=="disablePage")this.disablePage();
else if(a.type=="enablePage")this.enablePage();else if(a.type=="gotoPage"){var f=a.param&&a.param.page_number?a.param.page_number:a.param,e=typeof f=="string"?f.split(";"):[];e.length>1&&(f=e[Math.floor(Math.random()*e.length)]);f=parseInt(f);this.gotoPage(f)}else if(a.type=="callback")this.callback(a.object,a.param);else if(a.type=="map")this.map(a.param);else if(a.type=="gotoAndPlay")f=a.param&&a.param.frame_number?a.param.frame_number:a.param,e=typeof f=="string"?f.split(";"):[],e.length>1&&(f=
e[Math.floor(Math.random()*e.length)]),f=parseInt(f),isNaN(f)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",f=Mugeda.mapFrameNameId[f],f=parseInt(f)+1),this.gotoAndPlay(f);else if(a.type=="gotoAndPause"||a.type=="gotoAndStop")f=a.param&&a.param.frame_number?a.param.frame_number:a.param,e=typeof f=="string"?f.split(";"):[],e.length>1&&(f=e[Math.floor(Math.random()*e.length)]),f=parseInt(f),isNaN(f)&&(f=a.param&&a.param.frame_name?a.param.frame_name:"",f=Mugeda.mapFrameNameId[f],f=parseInt(f)+
1),this.gotoAndPause(f);else if(a.type=="call")MugedaMraid.makePhoneCall(a.param);else if(a.type=="sms")MugedaMraid.sendShortMessage(a.param);else if(a.type=="email")MugedaMraid.sendEmail(a.param);else if(a.type=="video")MugedaMraid.playVideo(a.param);else if(a.type=="stopVideo")MugedaMraid.stopVideo(a.param);else if(a.type=="audio")a.param.event=d,c=a.restart,window.Mugeda&&Mugeda.getMugedaObject&&(f=Mugeda.getMugedaObject(),f=Math.floor(f.scene.currentId),a.unit&&a.unit.frameStart==f&&(c=true)),
c=MugedaMraid.playAudio(a.param,c);else if(a.type=="picture")MugedaMraid.savePicture(a.param);else if(a.type=="calendar")MugedaMraid.addCalendarEvent(a.param);else if(a.type=="expand")MugedaMraid.expand(a.param.url,0,a.param);else if(a.type=="resize")MugedaMraid.expand("",1,a.param);else if(a.type=="stopAudio")Mugeda.stopAudio&&Mugeda.stopAudio(a.param);else if(a.type=="stopAllAudio")Mugeda.stopAudioAll&&Mugeda.stopAudioAll();else if(a.type=="submitForm"){var g=a.param,f=a.mugeda,e=g.submit_object,
i=g.submit_target||0;window._mrmcp=window._mrmcp||{};var g=i==0?_mrmcp.saveFormUrl||"http://weika.mugeda.com/server/cards.php/saveform":g.submit_url,h="",i=0;if(window._mrmcp&&window._mrmcp.creative_id)h=window._mrmcp.creative_id;else if(Mugeda&&Mugeda.data&&Mugeda.data.crid)h=Mugeda.data.crid,i=3;if(h==""&&/\/edit\/(\w+)\&?/.test(top.location.href))h=RegExp.$1,i=h.length<16?1:2;else if(h==""&&/id=(\w+)\&?/.test(window.location.search))i=3,h=RegExp.$1;if(h&&e){for(var e=e.split(","),i="crid="+h+"&mode="+
i,j=h=0;j<e.length;j++){var t=e[j],p=f.scene.getObjectByName(t);if((p=p?p.text||"":"")&&t)i+="&"+t+"="+p,h++}if(h==0)return;g+="?"+i;ajaxHelper({url:g,type:"jsonp",jsonp_callback:"form_callback",success:function(a){parseInt(a.status)},error:function(){}})}}f="actoin_type="+a.type+"&refid="+(new Date).getTime();for(item in a.param)f+="&"+item+"="+a.param[item];d=="click"&&window.event&&window.event.stopPropagation&&window.event.stopPropagation();c&&b&&a.param.event_name&&MugedaTracker.fireEvent({category:"interaction",
action:a.param.event_name,label:f,value:0})},processCloseButton:function(a,d){_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp;var b=d,c=null;if(!b)try{window!=window.parent?(b=window.parent.document,c=window.frameElement):b=document}catch(f){b=document}if(b){var e=null;try{e=window.parent.document,e.getElementById("mugeda_expanded")||e.createElement("div")}catch(g){return}var i=a||_mrmcp.display_mode,h=MugedaMraid.mraidReadyStatus==1?mraid.getPlacementType():"default",j=b.getElementById("mugeda_close_button");
if(!j)j=b.createElement("img"),j.id="mugeda_close_button",j.style.cursor="pointer",j.style.zIndex=99999,j.style.display="block",j.style.position="fixed",j.style.right="0",j.style.top="0",j.addEventListener("click",function(){if(MugedaMraid.mraidReadyStatus!=1){b.body.removeChild(j);i=="interstitial"&&c&&c.parentNode.removeChild(c);var a=b.getElementById("mugeda_expanded");a&&b.body.removeChild(a)}}),b.body.appendChild(j);if(h=="interstitial"||i=="auto"||i=="resize"||i=="expand"||i=="interstitial")j.src=
(_mrmcp.creative_path||"")+"close_button.png",j.onerror=function(){j.style.display="none"},j.onload=function(){j.style.display=h=="interstitial"||i!="auto"?"block":"none"}}},setupMobileActionCallback:function(a){MugedaBehavior.actionCallback=a},setupMobileActions:function(a,d,b){function c(a){var b=navigator.userAgent.toLowerCase().indexOf("android")>-1,c=b?15:20,e=b?5:10,h=function(a,h,g,j){if(Math.sqrt(a*a+h*h+g*g)>=(j?c:e)){a=(new Date).getTime();h=a-(MugedaBehavior.lastHitTime||0);if(!MugedaBehavior.lastHitTime||
h>200)MugedaBehavior.shakeNum++,MugedaBehavior.lastHitTime=a;else if(h>1E3)MugedaBehavior.shakeNum=0;if(MugedaBehavior.shakeNum>=(b?1:2)){for(var i in MugedaBehavior.shakeHash){a=MugedaBehavior.shakeHash[i];for(h=0;h<a.length;h++)info=a[h],g=info.object,g=g.displayObject?g.displayObject.realVisible:true,info.callback&&g&&(MugedaBehavior.processAction(info.behavior,info.behavior.event,true),info.callback())}MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,d.event);MugedaBehavior.shakeNum=
0}}},g=0,j=0,i=0;if(a.acceleration===null||a.acceleration.x===void 0||a.acceleration.y===void 0||a.acceleration.z===void 0||a.acceleration.x===null||a.acceleration.y===null||a.acceleration.z===null){if(a.accelerationIncludingGravity)g=a.accelerationIncludingGravity.x,j=a.accelerationIncludingGravity.y,i=a.accelerationIncludingGravity.z,h(g,j,i,1)}else g=a.acceleration.x,j=a.acceleration.y,i=a.acceleration.z,h(g,j,i,0)}var f=a.dataRef||a.aniData,e=a.dom?a.dom:window,g=isMobile()?"touchstart":"mousedown",
i=isMobile()?"touchend":"mouseup",h=isMobile()?"touchmove":"mousemove",j=null,t=0,p=0,l=0,o=0,q=0,u=0,n=function(a,b,d){var c=o-t,e=q-p,a=null;if(u-l<2E3&&(Math.abs(c)>32||Math.abs(e)>32))c=Math.atan2(-e,c)*180/Math.PI,-22.5<c&&c<=22.5?a="slide_right":22.5<c&&c<=67.5?a="slide_right_up":67.5<c&&c<=112.5?a="slide_up":112.5<c&&c<=157.5?a="slide_left_up":157.5<c||c<=-157.5?a="slide_left":-157.5<c&&c<=-112.5?a="slide_left_down":-112.5<c&&c<=-67.5?a="slide_down":-67.5<c&&c<=-22.5&&(a="slide_right_down");
c=b.slideHash?b.slideHash[a]||{}:{};b=c.behavior||{};c=c.callback;e=false;a&&b.event==a&&(e=true,MugedaBehavior.processAction(b,b.event,true),c&&c(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,b.event));j=null;return e||!d?a:null};if(d.event=="touch_start")a.touchstartBehavior=d,a.touchStartCallback=b;a.slideHooked||e.addEventListener(g,function(b){b.preventDefault();j=a;var c=b.targetTouches?b.targetTouches[0]:null;t=c?c.pageX:b.pageX;p=c?c.pageY:b.pageY;l=(new Date).getTime();
a.touchstartBehavior&&a.touchstartBehavior.event=="touch_start"&&a.dom&&a.dom.style.display!="none"&&(MugedaBehavior.processAction(a.touchstartBehavior,a.touchstartBehavior.event,true),a.touchStartCallback&&a.touchStartCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,a.touchstartBehavior.event))});if(d.event=="touch_end")a.touchendBehavior=d,a.touchendCallback=b;if(d.event.indexOf("slide_")==0)a.slideHash=a.slideHash||{},a.slideHash[d.event]={behavior:d,callback:b};a.slideHooked||
e.addEventListener(i,function(b){b.preventDefault();j=null;var c=b.changedTouches?b.changedTouches[0]:null;o=c?c.pageX:b.pageX;q=c?c.pageY:b.pageY;u=(new Date).getTime();n(e,a,true)&&b.stopPropagation();a.touchendBehavior&&a.touchendBehavior.event=="touch_end"&&a.dom.style.display!="none"&&(MugedaBehavior.processAction(a.touchendBehavior,a.touchendBehavior.event,true),a.touchendCallback&&a.touchendCallback(),MugedaBehavior.actionCallback&&MugedaBehavior.actionCallback(f,a.touchendBehavior.event))});
!a.slideHooked&&e.addEventListener(h,function(){});!a.slideHooked&&!isMobile()&&window.addEventListener(i,function(b){if(j)o=b.pageX,q=b.pageY,u=(new Date).getTime(),b.preventDefault(),n(e,a)&&b.stopPropagation()});a.slideHooked=true;if(d.event=="shake"&&window.DeviceMotionEvent){if(!window.mugedaShakeHooked)MugedaBehavior.shakeNum=0,window.addEventListener("devicemotion",c,false),window.mugedaShakeHooked=true;if(g=a.aniData?a.aniData.guid:null)MugedaBehavior.shakeHash[g]||(MugedaBehavior.shakeHash[g]=
[]),MugedaBehavior.shakeHash[g].push({object:a,callback:b,behavior:d})}}};

function mraidReady(){parseFloat(mraid.getVersion())-0.999>0?(MugedaMraid.mraidReadyStatus=1,_mrmcp=typeof _mrmcp=="undefined"?{}:_mrmcp,_mrmcp.display_mode&&(mraid.useCustomClose(true),MugedaBehavior.processCloseButton()),mraid.addEventListener("error",function(){}),mraid.addEventListener("stateChange",function(){var a=mraid.getState();MugedaMraid.setMraidState(a)}),mraid.addEventListener("sizeChange",function(){})):console.log("mraidReady is called, but with no correct version (>= 1.0) supported.")}
var mraidReadyTimeout,mraidTimeOut=100,mraidCounter=0;function readyListener(){typeof mraid==="undefined"?(mraidCounter++,mraidCounter<mraidTimeOut&&(mraidReadyTimeout=setTimeout(readyListener,100))):mraid.getState()==="loading"?mraid.addEventListener("ready",mraidReady):mraidReady()}readyListener();
try{var htmlDoc=document.getElementsByTagName("head").item(0),js=document.createElement("script"),s="js/mraid.js";js.setAttribute("type","text/javascript");js.setAttribute("src",s);htmlDoc.appendChild(js);js.onload=function(){};js.onerror=function(){}}catch(e$$22){alert(e$$22.toString())}
function genSessionId(a){for(var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=Number(+new Date).toString(36),c=0,f="",e=d.length;c<a;c++)f+=d[Math.floor(Math.random()*e)];return b+f.toLowerCase()}Mugeda=window.Mugeda||{};
Mugeda.Analytics=function(a,d){var b=[],c=0;window._mrmcp=window._mrmcp||{};var f=_mrmcp.impression_pixel?_mrmcp.impression_pixel.indexOf("%TRACKURL%")>=0?"":_mrmcp.impression_pixel:"",a=a||f||"http://cn-stat.mugeda.com/stats/c.gif",d=d||_mrmcp.eventUrl||a;this.setAccount=function(){};this.setCustomVar=function(a,c,d){a=a||0;b[a]&&delete b[a];b[a]={};b[a][c]=d||""};var e=function(a){if(document.cookie.length>0&&(c_start=document.cookie.indexOf(a+"="),c_start!=-1)){c_start=c_start+a.length+1;c_end=
document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end))}return""},g=function(){e("clientId");for(var a=[],c=0;c<b.length;c++)for(var d in b[c])a[c]=d+"="+encodeURIComponent(b[c][d]);return a.join("&")},i=function(){var a=location.pathname,b=/(?:\/animation\/edit)|(?:\/page\/edit)|(?:\/default\/preview\.html)|(?:\/client\/preview(?:_css3)?\.html)/;return!location.host||b.test(a)?false:true};this.trackPageview=function(b){if(i()){this.startTime=
(new Date).getTime();var d=a,f=new Image,p=d.indexOf("?")!=-1?"&":"?",l=_mrmcp.title||window._mrmma_title,o=+new Date,q=window.location.host,u=(_mrmcp.width||window._mrmma_width)+"x"+(_mrmcp.height||window._mrmma_height),n=window.location.href.slice(window.location.href.indexOf("/",8)),v=screen.width+"x"+screen.height,b=b||{};b.msv="0.1.0";b.msa="MU-A001";b.msh=q;b.mscs=u;b.msp=n;b.mssr=v;b.mssi=genSessionId(16);b.mscn=l;b.msct=o;b.crid=_mrmcp.creative_id||"";for(var A in b)b.hasOwnProperty(A)&&(this.setCustomVar(c,
A,b[A]),c++);b=e("msuid");if(!b)l=b=genSessionId(32),o=new Date,q=window.location.host.split("."),u=q.length,n="",n=u>=2?"."+q[u-2]+"."+q[u-1]:".mugeda.com",o.setDate(o.getDate()+3650),document.cookie="msuid="+escape(l)+(3650==null?"":";expires="+o.toGMTString())+"; domain="+n+"; path=/";this.setCustomVar(c++,"msuid",b);b=g();f.src=d+p+("mst=1&"+b)}};this.trackEvent=function(a){if(i()){var b=new Image,c=d,e=c.indexOf("?")!=-1?"&":"?",f=g(),a=a||{},o=(new Date).getTime(),q=o-this.startTime,u=encodeURIComponent(a.action||
"submit"),n=encodeURIComponent(a.categroy||"weika"),v=encodeURIComponent(a.label||""),a=parseInt(a.value)||0;b.src=c+e+f+"&mst=2&msts="+o+"&msetd="+q+"&msen="+u+"&msev="+a+"&msec="+n+"&msel="+v}}};try{window._mugeda_tracker=new Mugeda.Analytics,_mugeda_tracker.trackPageview()}catch(e$$23){}
function createFontFaceStyle(a,d,b,c,f){var e="cloudfont-"+d;b&&(e+="-"+b);var g=document.getElementById(e),i=Object.prototype.toString.call(c)==="[object Array]"&&typeof f==="function",h=function(a){return(a=RegExp("[?&]"+a+"=([^&#]*)").exec(window.location.href))?a[1]:0};a.toLowerCase()=="simhei"?a='"Microsoft YaHei", "\u5fae\u8f6f\u96c5\u9ed1", SimHei, sans-serif':b&&(a+="-"+b);if(g)return i&&f(a),a;for(var b=(b=h("fontApiType"))?b:3,g=["eot","eot","woff","ttf","svg"],j=d.indexOf("?")>-1?"&":"?",
h=window.bd_version||h("v")||0,t=[],p=c&&c.length,l=0,o=0,q=function(){var b=document.createElement("style"),c="@font-face {font-family:'"+a+"';\nsrc:"+t[0]+";\nsrc:"+t.slice(1).join(",\n")+";}",c=document.createTextNode(c);b.id=e;b.type="text/css";b.appendChild(c);document.head.appendChild(b)},u=function(b){ajax({url:b,success:function(){++o===p&&typeof f==="function"&&(q(),f(a))},error:function(){if(--p===0)throw f(false),"request font failed";}})},n=0,v=g.length;n<v;n++){var A=d+j+"format="+g[n]+
"&api_type="+b+"&v="+h,B="url("+A+")";if(n>0){var k=g[n];g[n]==="eot"?k="embedded-opentype":g[n]==="ttf"&&(k="truetype");B+=" format('"+k+"')"}t.push(B);i&&c.indexOf(k)>-1&&(l++,u(A))}if(i){if(l===0)throw"request type invalid";}else q();return a};
